package lima

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"

	"github.com/saeta-eth/watermelon/internal/config"
)

// shellMetacharacters contains characters that could be used for shell injection
const shellMetacharacters = ";|&$`\\"

// packageNameDangerous contains characters that are invalid in package names
const packageNameDangerous = ";|&$`\\(){}!~'\" \t\n"

// validateDomain checks that a domain string doesn't contain shell metacharacters
func validateDomain(domain string) error {
	if domain == "" {
		return fmt.Errorf("domain cannot be empty")
	}
	if strings.ContainsAny(domain, shellMetacharacters) {
		return fmt.Errorf("domain %q contains invalid characters", domain)
	}
	return nil
}

// validatePackageName checks that a package name doesn't contain shell metacharacters
func validatePackageName(name string) error {
	if name == "" {
		return fmt.Errorf("package name cannot be empty")
	}
	if strings.ContainsAny(name, packageNameDangerous) {
		return fmt.Errorf("package name %q contains invalid characters", name)
	}
	return nil
}

// findImageForCommand returns the container image that provides a given command
func findImageForCommand(tools map[string][]string, cmd string) string {
	for image, cmds := range tools {
		for _, c := range cmds {
			if c == cmd {
				return image
			}
		}
	}
	return ""
}

// validatePort checks that a port is within the valid range 1-65535
func validatePort(port int) error {
	if port < 1 || port > 65535 {
		return fmt.Errorf("port %d is out of valid range (1-65535)", port)
	}
	return nil
}

const limaTemplate = `# Auto-generated by watermelon - do not edit
vmType: vz
arch: default
cpus: {{ .CPUs }}
memory: {{ .Memory }}
disk: {{ .Disk }}

images:
  - location: "https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-arm64.img"
    arch: aarch64
  - location: "https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-amd64.img"
    arch: x86_64

mounts:
  - location: "{{ .ProjectDir }}"
    mountPoint: /project
    writable: true
{{- if .ToolsDir }}
  - location: "{{ .ToolsDir }}"
    mountPoint: /tools
    writable: false
{{- end }}

provision:
  - mode: system
    script: |
      set -e
      export DEBIAN_FRONTEND=noninteractive
{{- if .ProvisionBuilds }}
      # Build custom container images with provisioned packages
{{- range .ProvisionBuilds }}
      nerdctl rm -f {{ .CustomTag }}-build 2>/dev/null || true
      nerdctl run --name {{ .CustomTag }}-build {{ .BaseImage }} sh -c '{{ .InstallCmd }} {{ join .Packages " " }}'
      nerdctl commit {{ .CustomTag }}-build {{ .CustomTag }}
      nerdctl rm {{ .CustomTag }}-build
{{- end }}
{{- end }}
{{- if .Tools }}
      # Create wrapper scripts for containerized tools
{{- range $image, $cmds := .Tools }}
{{- range $cmd := $cmds }}
      printf '%s\n' '#!/bin/bash' 'if [ -t 0 ]; then' '    exec nerdctl run --rm -it --network=host -v /project:/project -w /project {{ $image }} {{ $cmd }} "$@"' 'else' '    exec nerdctl run --rm --network=host -v /project:/project -w /project {{ $image }} {{ $cmd }} "$@"' 'fi' > /usr/local/bin/{{ $cmd }}
      chmod +x /usr/local/bin/{{ $cmd }}
{{- end }}
{{- end }}
{{- end }}
{{- if .ProvisionBuilds }}
      # Discover and create wrapper scripts for binaries installed by provisioned packages
{{- range .ProvisionBuilds }}
      _WM_BASE_BINS=$(nerdctl run --rm {{ .BaseImage }} sh -c 'ls {{ .BinDirs }} 2>/dev/null' | sort)
      _WM_CUSTOM_BINS=$(nerdctl run --rm {{ .CustomTag }} sh -c 'ls {{ .BinDirs }} 2>/dev/null' | sort)
      echo "$_WM_BASE_BINS" > /tmp/_wm_base_bins.txt
      for _bin in $(echo "$_WM_CUSTOM_BINS" | grep -vxFf /tmp/_wm_base_bins.txt 2>/dev/null || true); do
        [ -f "/usr/local/bin/$_bin" ] && continue
        printf '%s\n' '#!/bin/bash' 'if [ -t 0 ]; then' '    exec nerdctl run --rm -it --network=host -v /project:/project -w /project {{ .CustomTag }} '"$_bin"' "$@"' 'else' '    exec nerdctl run --rm --network=host -v /project:/project -w /project {{ .CustomTag }} '"$_bin"' "$@"' 'fi' > "/usr/local/bin/$_bin"
        chmod +x "/usr/local/bin/$_bin"
      done
{{- end }}
{{- end }}
      # Network restrictions via iptables
{{- range .NetworkAllow }}
{{- if not (. | isWildcard) }}
      iptables -A OUTPUT -d {{ . }} -j ACCEPT
{{- end }}
{{- end }}
{{- if .NetworkAllow }}
      iptables -A OUTPUT -p tcp --dport 53 -j ACCEPT
      iptables -A OUTPUT -p udp --dport 53 -j ACCEPT
      iptables -A OUTPUT -o lo -j ACCEPT
      iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
      iptables -A OUTPUT -j REJECT
{{- end }}
{{- if .NetworkProcess }}
      # Per-process network namespaces
      apt-get update && apt-get install -y dnsmasq ipset
{{- $netIndex := 1 }}
{{- range $proc, $domains := .NetworkProcess }}
      # Setup namespace for {{ $proc }}
      ip netns add watermelon-{{ $proc }}

      # Create veth pair
      ip link add veth-{{ $proc }} type veth peer name veth-{{ $proc }}-ns
      ip link set veth-{{ $proc }}-ns netns watermelon-{{ $proc }}

      # Configure host side
      ip addr add 10.200.{{ $netIndex }}.1/24 dev veth-{{ $proc }}
      ip link set veth-{{ $proc }} up

      # Configure namespace side
      ip netns exec watermelon-{{ $proc }} ip addr add 10.200.{{ $netIndex }}.2/24 dev veth-{{ $proc }}-ns
      ip netns exec watermelon-{{ $proc }} ip link set veth-{{ $proc }}-ns up
      ip netns exec watermelon-{{ $proc }} ip link set lo up
      ip netns exec watermelon-{{ $proc }} ip route add default via 10.200.{{ $netIndex }}.1

      # Enable forwarding and NAT for this namespace
      iptables -t nat -A POSTROUTING -s 10.200.{{ $netIndex }}.0/24 -j MASQUERADE
      echo 1 > /proc/sys/net/ipv4/ip_forward

      # Create ipset for wildcard domains
      ipset create watermelon-{{ $proc }}-allow hash:ip

      # Apply iptables rules in namespace (general + process-specific)
{{- range $.NetworkAllow }}
{{- if not (. | isWildcard) }}
      ip netns exec watermelon-{{ $proc }} iptables -A OUTPUT -d {{ . }} -j ACCEPT
{{- end }}
{{- end }}
{{- range $domains }}
{{- if not (. | isWildcard) }}
      ip netns exec watermelon-{{ $proc }} iptables -A OUTPUT -d {{ . }} -j ACCEPT
{{- end }}
{{- end }}
      ip netns exec watermelon-{{ $proc }} iptables -A OUTPUT -m set --match-set watermelon-{{ $proc }}-allow dst -j ACCEPT
      ip netns exec watermelon-{{ $proc }} iptables -A OUTPUT -p tcp --dport 53 -j ACCEPT
      ip netns exec watermelon-{{ $proc }} iptables -A OUTPUT -p udp --dport 53 -j ACCEPT
      ip netns exec watermelon-{{ $proc }} iptables -A OUTPUT -o lo -j ACCEPT
      ip netns exec watermelon-{{ $proc }} iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
      ip netns exec watermelon-{{ $proc }} iptables -A OUTPUT -j REJECT

      # Configure dnsmasq for {{ $proc }} wildcard domains
      mkdir -p /etc/watermelon
      cat > /etc/watermelon/{{ $proc }}-dns.conf << 'DNSCONF'
# dnsmasq config for {{ $proc }}
port=53
bind-interfaces
listen-address=10.200.{{ $netIndex }}.1
server=8.8.8.8
server=8.8.4.4
{{- range $domains }}
{{- if . | isWildcard }}
ipset=/{{ . | baseDomain }}/watermelon-{{ $proc }}-allow
{{- end }}
{{- end }}
DNSCONF
      # Start dnsmasq for this namespace
      dnsmasq --conf-file=/etc/watermelon/{{ $proc }}-dns.conf
      # Configure namespace to use this DNS
      mkdir -p /etc/netns/watermelon-{{ $proc }}
      echo "nameserver 10.200.{{ $netIndex }}.1" > /etc/netns/watermelon-{{ $proc }}/resolv.conf

      # Create wrapper script for {{ $proc }}
      cat > /usr/local/bin/{{ $proc }} << 'WRAPPER'
#!/bin/bash
# Find the real binary (skip this wrapper)
REAL_BIN=$(which -a {{ $proc }} 2>/dev/null | grep -v /usr/local/bin/{{ $proc }} | head -1)
if [ -z "$REAL_BIN" ]; then
    echo "Error: {{ $proc }} not found in PATH" >&2
    exit 1
fi
exec ip netns exec watermelon-{{ $proc }} "$REAL_BIN" "$@"
WRAPPER
      chmod +x /usr/local/bin/{{ $proc }}
{{- $netIndex = add $netIndex 1 }}
{{- end }}
{{- end }}
  - mode: user
    script: |
      if ! grep -q 'cd /project' ~/.bashrc 2>/dev/null; then
        echo '[ -d /project ] && cd /project' >> ~/.bashrc
      fi

networks: []

portForwards:
{{- range .PortForwards }}
  - guestPort: {{ . }}
    hostPort: {{ . }}
{{- end }}
  # Disable automatic port forwarding for security isolation
  - ignore: true
    guestIP: "0.0.0.0"
    guestPortRange: [1, 65535]
  - ignore: true
    guestIP: "127.0.0.1"
    guestPortRange: [1, 65535]
`

type provisionBuild struct {
	BaseImage  string
	CustomTag  string
	InstallCmd string
	Packages   []string
	BinDirs    string
}

type templateData struct {
	CPUs            int
	Memory          string
	Disk            string
	ProjectDir      string
	ToolsDir        string
	NetworkAllow    []string
	NetworkProcess  map[string][]string
	PortForwards    []int
	Tools           map[string][]string
	ProvisionBuilds []provisionBuild
}

// GenerateConfig creates Lima YAML from watermelon config
func GenerateConfig(cfg *config.Config, projectDir string) (string, error) {
	// Validate network allow domains
	for _, domain := range cfg.Network.Allow {
		if err := validateDomain(domain); err != nil {
			return "", fmt.Errorf("invalid network allow domain: %w", err)
		}
	}

	// Validate network process names and domains
	for processName, domains := range cfg.Network.Process {
		if processName == "" {
			return "", fmt.Errorf("process name cannot be empty")
		}
		if strings.ContainsAny(processName, shellMetacharacters+" /") {
			return "", fmt.Errorf("invalid process name %q: contains invalid characters", processName)
		}
		for _, domain := range domains {
			if err := validateDomain(domain); err != nil {
				return "", fmt.Errorf("invalid domain for process %q: %w", processName, err)
			}
		}
	}

	// Validate port forwards
	for _, port := range cfg.Ports.Forward {
		if err := validatePort(port); err != nil {
			return "", fmt.Errorf("invalid port forward: %w", err)
		}
	}

	// Build provision data: custom images and tool image overrides
	type provSpec struct {
		pkgs       []string
		cmd        string
		installCmd string
		tag        string
		binDirs    string
	}
	specs := []provSpec{
		{cfg.Provision.Npm, "npm", "npm install -g", "watermelon-npm", "/usr/local/bin"},
		{cfg.Provision.Pip, "pip", "pip install", "watermelon-pip", "/usr/local/bin"},
		{cfg.Provision.Cargo, "cargo", "cargo install", "watermelon-cargo", "/usr/local/cargo/bin /usr/local/bin"},
		{cfg.Provision.Go, "go", "go install", "watermelon-go", "/go/bin /usr/local/bin"},
		{cfg.Provision.Gem, "gem", "gem install", "watermelon-gem", "/usr/local/bin"},
	}

	var provisionBuilds []provisionBuild
	imageOverrides := make(map[string]string)

	for _, spec := range specs {
		if len(spec.pkgs) == 0 {
			continue
		}
		for _, pkg := range spec.pkgs {
			if err := validatePackageName(pkg); err != nil {
				return "", fmt.Errorf("invalid %s package: %w", spec.cmd, err)
			}
		}
		img := findImageForCommand(cfg.Tools, spec.cmd)
		if img == "" {
			return "", fmt.Errorf("provision.%s requires %s in [tools]; add a container image that provides %s", spec.cmd, spec.cmd, spec.cmd)
		}
		imageOverrides[img] = spec.tag
		provisionBuilds = append(provisionBuilds, provisionBuild{
			BaseImage:  img,
			CustomTag:  spec.tag,
			InstallCmd: spec.installCmd,
			Packages:   spec.pkgs,
			BinDirs:    spec.binDirs,
		})
	}

	// Apply image overrides so tool wrappers use custom images with packages pre-installed
	tools := make(map[string][]string)
	for image, cmds := range cfg.Tools {
		if override, ok := imageOverrides[image]; ok {
			tools[override] = cmds
		} else {
			tools[image] = cmds
		}
	}

	funcMap := template.FuncMap{
		"add": func(a, b int) int { return a + b },
		"isWildcard": func(s string) bool {
			return strings.HasPrefix(s, "*.")
		},
		"baseDomain": func(s string) string {
			return strings.TrimPrefix(s, "*.")
		},
		"join": strings.Join,
	}
	tmpl, err := template.New("lima").Funcs(funcMap).Parse(limaTemplate)
	if err != nil {
		return "", fmt.Errorf("parsing template: %w", err)
	}

	data := templateData{
		CPUs:            cfg.Resources.CPUs,
		Memory:          convertMemory(cfg.Resources.Memory),
		Disk:            convertDisk(cfg.Resources.Disk),
		ProjectDir:      projectDir,
		ToolsDir:        "",
		NetworkAllow:    cfg.Network.Allow,
		NetworkProcess:  cfg.Network.Process,
		PortForwards:    cfg.Ports.Forward,
		Tools:           tools,
		ProvisionBuilds: provisionBuilds,
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("executing template: %w", err)
	}

	return buf.String(), nil
}

// convertMemory converts "4GB" to "4GiB" for Lima
func convertMemory(mem string) string {
	return strings.Replace(mem, "GB", "GiB", 1)
}

// convertDisk converts "20GB" to "20GiB" for Lima
func convertDisk(disk string) string {
	return strings.Replace(disk, "GB", "GiB", 1)
}
