package lima

import (
	"bytes"
	"crypto/sha256"
	"encoding/base64"
	"errors"
	"fmt"
	"io"
	"net/netip"
	"os"
	"path"
	"path/filepath"
	"runtime"
	"sort"
	"strconv"
	"strings"
	"syscall"
	"text/template"
	"unicode/utf8"

	"github.com/saeta-eth/watermelon/internal/config"
	"golang.org/x/sys/unix"
)

// validatePort checks that a port is within the valid range 1-65535
func validatePort(port int) error {
	if port < 1 || port > 65535 {
		return fmt.Errorf("port %d is out of valid range (1-65535)", port)
	}
	return nil
}

// processKernelID returns a deterministic identifier short enough for Linux
// interfaces (IFNAMSIZ is 16 including the trailing NUL) and other kernel names.
func processKernelID(name string) string {
	sum := sha256.Sum256([]byte(name))
	return fmt.Sprintf("%x", sum[:6])
}

func buildProcessKernelIDs(processNames []string, identifier func(string) string) (map[string]string, error) {
	ids := make(map[string]string, len(processNames))
	owners := make(map[string]string, len(processNames))
	for _, processName := range processNames {
		id := identifier(processName)
		if owner, exists := owners[id]; exists {
			return nil, fmt.Errorf("network process names %q and %q have colliding kernel identifiers", owner, processName)
		}
		owners[id] = processName
		ids[processName] = id
	}
	return ids, nil
}

const limaTemplate = `# Auto-generated by watermelon - do not edit
minimumLimaVersion: {{ .MinimumLimaVersion }}
vmType: {{ .VMType }}
arch: default
cpus: {{ .CPUs }}
memory: {{ yamlQuote .Memory }}
disk: {{ yamlQuote .Disk }}

user:
  name: {{ yamlQuote .VMUser }}
  uid: {{ .VMUserUID }}
  home: {{ yamlQuote .VMUserHome }}
  shell: /bin/bash

images:
{{- if eq .Image "ubuntu-24.04" }}
  - location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-arm64.img"
    arch: aarch64
  - location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img"
    arch: x86_64
{{- else }}
  - location: "https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-arm64.img"
    arch: aarch64
  - location: "https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-amd64.img"
    arch: x86_64
{{- end }}

{{- if or .MountProject .Mounts .BootstrapHostDir .LogHostDir }}
mounts:
{{- if .MountProject }}
  - location: {{ yamlQuote .ProjectDir }}
    mountPoint: /project
    writable: true
{{- end }}
{{- range .Mounts }}
  - location: {{ yamlQuote .Location }}
    mountPoint: {{ yamlQuote .Target }}
    writable: {{ .Writable }}
{{- end }}
{{- if .BootstrapHostDir }}
  - location: {{ yamlQuote .BootstrapHostDir }}
    mountPoint: /mnt/watermelon/bootstrap
    writable: false
{{- end }}
{{- if .LogHostDir }}
  - location: {{ yamlQuote .LogHostDir }}
    mountPoint: /mnt/watermelon/state
    writable: true
{{- end }}
{{- else }}
mounts: []
{{- end }}

provision:
  - mode: system
    script: |
      #!/bin/bash
      set -e
      set -o pipefail
      export PATH=/usr/sbin:/usr/bin:/sbin:/bin
      export DEBIAN_FRONTEND=noninteractive

      # Lima records provision failures but continues with later scripts and
      # may still report the guest as ready. Reset Watermelon's own per-boot
      # attestation before doing any work so a partial retry cannot inherit a
      # success marker from an earlier provisioning pass.
      /bin/rm -f -- /run/watermelon-provisioning-complete
      /bin/rm -rf -- /run/watermelon-provisioning
      /usr/bin/install -d -o root -g root -m 0700 /run/watermelon-provisioning
      if [ -f /run/watermelon-policy-applied ]; then
        exit 0
      fi

      wm_delete_jump() {
        _wm_table="$1"
        _wm_parent="$2"
        _wm_child="$3"
        while iptables -w -t "$_wm_table" -D "$_wm_parent" -j "$_wm_child" 2>/dev/null; do :; done
      }

      wm_reset_root_policy() {
        wm_delete_jump filter OUTPUT WM_OUTPUT
        iptables -w -F WM_OUTPUT 2>/dev/null || true
        iptables -w -X WM_OUTPUT 2>/dev/null || true
        wm_delete_jump nat OUTPUT WM_DNS_OUT
        iptables -w -t nat -F WM_DNS_OUT 2>/dev/null || true
        iptables -w -t nat -X WM_DNS_OUT 2>/dev/null || true
{{- if eq .Enforcement "ask" }}
        while iptables -w -D INPUT -p udp --sport 53 -j NFQUEUE --queue-num 1 2>/dev/null; do :; done
{{- end }}
      }

      _WM_FIRST_BOOT=false
      if [ ! -f /var/lib/watermelon/bootstrap-complete ]; then
        _WM_FIRST_BOOT=true
      fi
      # A completed legacy/final bootstrap necessarily completed the trusted
      # stage; never reopen networking merely because the newer marker is absent.
      if [ -f /var/lib/watermelon/bootstrap-complete ] && [ ! -f /var/lib/watermelon/trusted-bootstrap-complete ]; then
        mkdir -p /var/lib/watermelon
        touch /var/lib/watermelon/trusted-bootstrap-complete
      fi

      # The Lima identity is declared explicitly in this immutable config.
      # Privileged launch helpers bake it and never accept a caller-selected
      # user or group.
      _WM_USER={{ .VMUser }}
      _WM_UID=$(/usr/bin/id -u "$_WM_USER")
      _WM_GID=$(/usr/bin/id -g "$_WM_USER")
      _WM_HOME=$(/usr/bin/getent passwd "$_WM_USER" | /usr/bin/cut -d: -f6)
      case "$_WM_UID:$_WM_GID" in
        *[!0-9:]*)
          echo "unsafe Lima VM numeric identity" >&2
          exit 1
          ;;
      esac
      if [ "$_WM_UID" != "{{ .VMUserUID }}" ] || [ "$_WM_GID" = 0 ]; then
        echo "Lima VM identity unexpectedly has privileged numeric IDs" >&2
        exit 1
      fi
      if [ "$_WM_HOME" != "{{ .VMUserHome }}" ]; then
        echo "Lima VM home directory does not match the immutable policy identity" >&2
        exit 1
      fi

      # Lima grants its login user broad passwordless sudo by default. A later
      # sudoers entry revokes it before any workload can run, then grants only
      # the fixed, root-owned process launchers generated by this policy.
      wm_install_sudoers() {
        _WM_SUDOERS_TMP=$(/usr/bin/mktemp /etc/sudoers.d/.99-watermelon.XXXXXX)
        /bin/cat > "$_WM_SUDOERS_TMP" << SUDOERS
      $_WM_USER ALL=(ALL:ALL) !ALL
{{- range $proc := .SortedProcessNames }}
{{- $kernelID := index $.ProcessKernelIDs $proc }}
      $_WM_USER ALL=(root:root) NOPASSWD:NOSETENV: /usr/local/libexec/watermelon/process-{{ $kernelID }}
{{- end }}
      SUDOERS
        /bin/chown root:root "$_WM_SUDOERS_TMP"
        /bin/chmod 0440 "$_WM_SUDOERS_TMP"
        /usr/sbin/visudo -cf "$_WM_SUDOERS_TMP"
        /bin/mv -f "$_WM_SUDOERS_TMP" /etc/sudoers.d/99-watermelon
        /usr/sbin/visudo -cf /etc/sudoers
      }
      wm_install_sudoers

      /bin/mkdir -p /usr/local/libexec/watermelon /var/empty
      /bin/chown root:root /usr/local/libexec /usr/local/libexec/watermelon /var/empty
      /bin/chmod 0755 /usr/local/libexec /usr/local/libexec/watermelon /var/empty
{{- if .BootstrapImages }}
      # Resolve Lima's nerdctl without consulting aliases or shell functions,
      # verify the binary, then preserve a private root-owned copy. This keeps
      # privileged helpers independent of PATH, caller environment, and tool
      # wrappers that may later be installed in /usr/local/bin.
      _WM_NERDCTL=/usr/local/libexec/watermelon/nerdctl
      _WM_NERDCTL_VALID=false
      if [ -f "$_WM_NERDCTL" ] && [ ! -L "$_WM_NERDCTL" ] && [ -x "$_WM_NERDCTL" ] && [ "$(/usr/bin/stat -c %u "$_WM_NERDCTL")" = 0 ] && [ "$(/usr/bin/od -An -t x1 -N4 "$_WM_NERDCTL" | /usr/bin/tr -d ' \n')" = 7f454c46 ]; then
        _WM_NERDCTL_VALID=true
      fi
      if [ "$_WM_NERDCTL_VALID" != true ]; then
        if [ -f /var/lib/watermelon/trusted-bootstrap-complete ]; then
          echo "the private verified nerdctl is missing or invalid after trusted bootstrap" >&2
          exit 1
        fi
        _WM_NERDCTL_SOURCE=""
        for _WM_NERDCTL_CANDIDATE in /usr/local/bin/nerdctl /usr/bin/nerdctl; do
          [ -e "$_WM_NERDCTL_CANDIDATE" ] || continue
          _WM_NERDCTL_CANDIDATE=$(/usr/bin/readlink -f -- "$_WM_NERDCTL_CANDIDATE")
          if [ -f "$_WM_NERDCTL_CANDIDATE" ] && [ ! -L "$_WM_NERDCTL_CANDIDATE" ] && [ -x "$_WM_NERDCTL_CANDIDATE" ] && [ "$(/usr/bin/stat -c %u "$_WM_NERDCTL_CANDIDATE")" = 0 ] && [ "$(/usr/bin/od -An -t x1 -N4 "$_WM_NERDCTL_CANDIDATE" | /usr/bin/tr -d ' \n')" = 7f454c46 ]; then
            _WM_NERDCTL_SOURCE=$_WM_NERDCTL_CANDIDATE
            break
          fi
        done
        case "$_WM_NERDCTL_SOURCE" in
          ""{{ if .MountProject }}|/project|/project/*{{ end }}|/mnt/watermelon|/mnt/watermelon/*|/tmp|/tmp/*|/var/tmp|/var/tmp/*|/run/user|/run/user/*|/dev/shm|/dev/shm/*|"$_WM_HOME"|"$_WM_HOME"/*)
            echo "nerdctl resolved to an unsafe guest-writable location" >&2
            exit 1
            ;;
        esac
        if [ ! -f "$_WM_NERDCTL_SOURCE" ] || [ -L "$_WM_NERDCTL_SOURCE" ] || [ ! -x "$_WM_NERDCTL_SOURCE" ] || [ "$(/usr/bin/stat -c %u "$_WM_NERDCTL_SOURCE")" != 0 ] || [ "$(/usr/bin/od -An -t x1 -N4 "$_WM_NERDCTL_SOURCE" | /usr/bin/tr -d ' \n')" != 7f454c46 ]; then
          echo "nerdctl must resolve to a root-owned regular ELF executable" >&2
          exit 1
        fi
        _WM_NERDCTL_TMP=$(/usr/bin/mktemp /usr/local/libexec/watermelon/.nerdctl.XXXXXX)
        /usr/bin/install -o root -g root -m 0755 "$_WM_NERDCTL_SOURCE" "$_WM_NERDCTL_TMP"
        /bin/mv -f "$_WM_NERDCTL_TMP" "$_WM_NERDCTL"
      fi
      wm_nerdctl() {
        /usr/sbin/runuser -u "$_WM_USER" -- /usr/bin/env -i \
          HOME="$_WM_HOME" USER="$_WM_USER" LOGNAME="$_WM_USER" \
          PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
          XDG_RUNTIME_DIR="/run/user/$_WM_UID" \
          "$_WM_NERDCTL" "$@"
      }
      wm_root_nerdctl() {
        /usr/bin/env -i HOME=/var/empty XDG_CONFIG_HOME=/var/empty \
          PATH=/usr/sbin:/usr/bin:/sbin:/bin \
          "$_WM_NERDCTL" --address /run/containerd/containerd.sock --namespace default "$@"
      }
{{- end }}
{{- if .NetworkProcessRules }}
      # Reconcile any partial per-process state before this run. Kernel state is
      # ephemeral across reboots, but a failed same-boot provision may leave it.
{{- $cleanupIndex := 1 }}
{{- range $proc := .SortedProcessNames }}
{{- $kernelID := index $.ProcessKernelIDs $proc }}
      _WM_PROC_DNS_PID=""
      if [ -f /run/watermelon-process-{{ $kernelID }}-dns.pid ]; then
        _WM_PROC_DNS_PID=$(cat /run/watermelon-process-{{ $kernelID }}-dns.pid 2>/dev/null || true)
      fi
      if [ -n "$_WM_PROC_DNS_PID" ] && [ "$(cat "/proc/$_WM_PROC_DNS_PID/comm" 2>/dev/null || true)" = dnsmasq ]; then
        kill "$_WM_PROC_DNS_PID" 2>/dev/null || true
      fi
      rm -f /run/watermelon-process-{{ $kernelID }}-dns.pid
      while iptables -w -D FORWARD -i wh-{{ $kernelID }} -j WMF_{{ $kernelID }} 2>/dev/null; do :; done
      while iptables -w -D FORWARD -o wh-{{ $kernelID }} -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT 2>/dev/null; do :; done
      iptables -w -F WMF_{{ $kernelID }} 2>/dev/null || true
      iptables -w -X WMF_{{ $kernelID }} 2>/dev/null || true
      while iptables -w -t nat -D PREROUTING -i wh-{{ $kernelID }} -p tcp --dport 53 -j DNAT --to-destination 10.200.{{ $cleanupIndex }}.1:53 2>/dev/null; do :; done
      while iptables -w -t nat -D PREROUTING -i wh-{{ $kernelID }} -p udp --dport 53 -j DNAT --to-destination 10.200.{{ $cleanupIndex }}.1:53 2>/dev/null; do :; done
      while iptables -w -t nat -D POSTROUTING -s 10.200.{{ $cleanupIndex }}.0/24 -j MASQUERADE 2>/dev/null; do :; done
      ip netns delete wmns-{{ $kernelID }} 2>/dev/null || true
      ip link delete wh-{{ $kernelID }} 2>/dev/null || true
{{- $cleanupIndex = add $cleanupIndex 1 }}
{{- end }}
{{- end }}

      if [ ! -f /var/lib/watermelon/trusted-bootstrap-complete ]; then
        # A failed bootstrap may have left a partial full policy behind. Return
        # to the intentional trusted-bootstrap state before controlled downloads.
        wm_reset_root_policy
        wm_delete_jump filter OUTPUT WM_EARLY
        iptables -w -P OUTPUT ACCEPT
{{- if .RejectUnknown }}
        # Install, but do not start, the fail-closed policy used at the beginning
        # of every subsequent boot. First bootstrap remains intentionally open.
        cat > /usr/local/sbin/watermelon-early-firewall << 'EARLYFIREWALL'
      #!/bin/sh
      set -eu
      PATH=/usr/sbin:/usr/bin:/sbin:/bin
      export PATH
      iptables -w -P OUTPUT DROP
      iptables -w -P FORWARD DROP
      if command -v ip6tables >/dev/null 2>&1; then
        ip6tables -w -P OUTPUT DROP
        ip6tables -w -P FORWARD DROP
      fi
      iptables -w -N WM_EARLY 2>/dev/null || true
      iptables -w -F WM_EARLY
      while iptables -w -D OUTPUT -j WM_EARLY 2>/dev/null; do :; done
      iptables -w -A WM_EARLY -o lo -j ACCEPT
      iptables -w -A WM_EARLY -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
      # DHCPv4 is the only pre-policy network bootstrap traffic permitted.
      iptables -w -A WM_EARLY -p udp --sport 68 --dport 67 -d 255.255.255.255 -j ACCEPT
      iptables -w -A WM_EARLY -j DROP
      iptables -w -I OUTPUT 1 -j WM_EARLY
      if [ -e /proc/sys/net/ipv6/conf/all/disable_ipv6 ]; then
        sysctl -q -w net.ipv6.conf.all.disable_ipv6=1
        sysctl -q -w net.ipv6.conf.default.disable_ipv6=1
      fi
      EARLYFIREWALL
        chmod 0755 /usr/local/sbin/watermelon-early-firewall
        cat > /etc/systemd/system/watermelon-early-firewall.service << 'EARLYSERVICE'
      [Unit]
      Description=Watermelon early fail-closed network policy
      DefaultDependencies=no
      Wants=local-fs.target network-pre.target
      After=local-fs.target systemd-modules-load.service systemd-sysctl.service
      Before=network-pre.target shutdown.target
      Conflicts=shutdown.target
      ConditionPathExists=/var/lib/watermelon/trusted-bootstrap-complete

      [Service]
      Type=oneshot
      ExecStart=/usr/local/sbin/watermelon-early-firewall
      RemainAfterExit=yes

      [Install]
      WantedBy=sysinit.target
      EARLYSERVICE
        mkdir -p /etc/systemd/system/systemd-networkd.service.d
        cat > /etc/systemd/system/systemd-networkd.service.d/watermelon-early-firewall.conf << 'NETWORKDDROPIN'
      [Unit]
      Requires=watermelon-early-firewall.service
      After=watermelon-early-firewall.service
      NETWORKDDROPIN
        mkdir -p /etc/sysctl.d
        cat > /etc/sysctl.d/99-watermelon-network.conf << 'SYSCTL'
      net.ipv6.conf.all.disable_ipv6 = 1
      net.ipv6.conf.default.disable_ipv6 = 1
      SYSCTL
        systemctl daemon-reload
        systemctl enable watermelon-early-firewall.service
{{- end }}
        # A failed first bootstrap may have left the restrictive resolver
        # enabled. Restore host-provided DNS before trusted downloads retry.
        systemctl stop watermelon-dns.service 2>/dev/null || true
        rm -f /etc/systemd/resolved.conf.d/watermelon.conf
        systemctl restart systemd-resolved
        _WM_DNS_READY=false
        for _i in $(seq 1 30); do
          if getent ahostsv4 dns.google >/dev/null 2>&1; then
            _WM_DNS_READY=true
            break
          fi
          sleep 1
        done
        if [ "$_WM_DNS_READY" != true ]; then
          echo "trusted bootstrap DNS did not become ready" >&2
          exit 1
        fi

        # Trusted bootstrap prerequisites. Configured package installation is
        # deliberately deferred until after policy becomes active.
        apt-get update && apt-get install -y dnsmasq-base ipset
        if ! id -u watermelon-dns >/dev/null 2>&1; then
          useradd --system --user-group --no-create-home --shell /usr/sbin/nologin watermelon-dns
        fi
{{- if eq .Enforcement "ask" }}
        apt-get install -y libnetfilter-queue1
{{- end }}
{{- if .BootstrapImages }}
        # Pull configured base images while trusted bootstrap has network.
{{- range .BootstrapImages }}
        wm_nerdctl pull "{{ . }}"
{{- end }}
{{- end }}
{{- if .RejectUnknown }}
        # Snapshot configured exact names while trusted DNS is available. These
        # files let enforcing reboots construct rules without a temporary DNS hole.
        mkdir -p /etc/watermelon
        wm_capture_dns_host() {
          _WM_HOST="$1"
          _WM_DEST="$2"
          _WM_CAPTURE=$(mktemp)
          if ! getent ahostsv4 "$_WM_HOST" | awk -v host="$_WM_HOST" '!seen[$1]++ { print $1, host }' > "$_WM_CAPTURE"; then
            rm -f "$_WM_CAPTURE"
            echo "failed to resolve required exact host $_WM_HOST" >&2
            return 1
          fi
          if [ ! -s "$_WM_CAPTURE" ]; then
            rm -f "$_WM_CAPTURE"
            echo "required exact host $_WM_HOST has no IPv4 address" >&2
            return 1
          fi
          cat "$_WM_CAPTURE" >> "$_WM_DEST"
          rm -f "$_WM_CAPTURE"
        }
        _WM_ALLOWED_HOSTS=$(mktemp /etc/watermelon/allowed-hosts.XXXXXX)
{{- range .DNSExactHosts }}
        wm_capture_dns_host "{{ . }}" "$_WM_ALLOWED_HOSTS"
{{- end }}
        chmod 0644 "$_WM_ALLOWED_HOSTS"
        mv -f "$_WM_ALLOWED_HOSTS" /etc/watermelon/allowed-hosts
{{- range $proc := .SortedProcessNames }}
{{- $kernelID := index $.ProcessKernelIDs $proc }}
        _WM_PROCESS_HOSTS=$(mktemp /etc/watermelon/process-{{ $kernelID }}-allowed-hosts.XXXXXX)
{{- $exactHosts := index $.ProcessDNSExactHosts $proc }}
{{- range $exactHosts }}
        wm_capture_dns_host "{{ . }}" "$_WM_PROCESS_HOSTS"
{{- end }}
        chmod 0644 "$_WM_PROCESS_HOSTS"
        mv -f "$_WM_PROCESS_HOSTS" /etc/watermelon/process-{{ $kernelID }}-allowed-hosts
{{- end }}
{{- end }}
{{- if .RejectUnknown }}
        # Close trusted-bootstrap networking before committing its durable
        # marker. If provisioning is interrupted after this point, the VM is
        # already fail-closed and the early boot unit will remain enabled.
        /usr/local/sbin/watermelon-early-firewall
        iptables -w -C OUTPUT -j WM_EARLY
        if ! iptables -w -S OUTPUT | /usr/bin/grep -qx -- '-P OUTPUT DROP'; then
          echo "early firewall did not establish a fail-closed OUTPUT policy" >&2
          exit 1
        fi
{{- end }}
        mkdir -p /var/lib/watermelon
        touch /var/lib/watermelon/trusted-bootstrap-complete
      else
        # Stop managed DNS until ephemeral ipsets and firewall rules are rebuilt.
        systemctl stop watermelon-dns.service 2>/dev/null || true
        wm_reset_root_policy
      fi
{{- if .RejectUnknown }}
      # Preserve the early boot default while the complete policy is assembled.
      systemctl restart watermelon-early-firewall.service
{{- else }}
      iptables -w -P OUTPUT ACCEPT
{{- end }}
      _WM_DNS_UID=$(id -u watermelon-dns)
{{- if .NetworkProcessRules }}
      # Enable rootful containerd for namespace-aware containers.
      # Rootless containerd uses slirp4netns (bypasses VM iptables), so we need
      # rootful mode to use --network=ns:<path> for per-process namespaces.
      systemctl enable --now containerd
{{- end }}
{{- if .LogUnknown }}
      if [ "$_WM_FIRST_BOOT" = true ]; then
      # Forward kernel firewall logs through a root-owned helper. It walks the
      # destination without following symlinks and holds the verified append
      # descriptor open, so a guest path swap cannot redirect journal output
      # into another mounted project file.
{{- if .LogInGuest }}
      /bin/mkdir -p -- {{ shellQuote .LogDir }}
      /bin/chown "$_WM_USER:$_WM_USER" -- {{ shellQuote .LogDir }}
      /bin/chmod 0700 -- {{ shellQuote .LogDir }}
{{- end }}
      if [ ! -x /usr/bin/python3 ]; then
        echo "supported Ubuntu image is missing /usr/bin/python3 for the secure log writer" >&2
        exit 1
      fi
      _WM_LOG_WRITER_TMP=$(/usr/bin/mktemp /usr/local/libexec/watermelon/.log-writer.XXXXXX)
      /bin/cat > "$_WM_LOG_WRITER_TMP" << 'LOGWRITER'
      #!/usr/bin/python3
      import os
      import stat
      import subprocess
      import sys

      log_path = {{ yamlQuote .LogPath }}
      max_log_bytes = 16 * 1024 * 1024
      directory_flags = os.O_RDONLY | os.O_DIRECTORY | os.O_CLOEXEC | os.O_NOFOLLOW

      def open_log_parent(target):
          components = [part for part in os.path.dirname(target).split("/") if part]
          current = os.open("/", directory_flags)
          try:
              for index, component in enumerate(components):
                  try:
                      next_fd = os.open(component, directory_flags, dir_fd=current)
                  except FileNotFoundError:
                      if index != len(components) - 1:
                          raise
                      os.mkdir(component, mode=0o700, dir_fd=current)
                      next_fd = os.open(component, directory_flags, dir_fd=current)
                  os.close(current)
                  current = next_fd
              info = os.fstat(current)
              if not stat.S_ISDIR(info.st_mode) or info.st_uid != os.geteuid():
                  raise RuntimeError("log directory must be a real directory owned by the VM user")
              os.fchmod(current, 0o700)
              return current, os.path.basename(target)
          except BaseException:
              os.close(current)
              raise

      parent_fd, filename = open_log_parent(log_path)
      try:
          log_fd = os.open(
              filename,
              os.O_WRONLY | os.O_APPEND | os.O_CREAT | os.O_CLOEXEC | os.O_NOFOLLOW | os.O_NONBLOCK,
              0o600,
              dir_fd=parent_fd,
          )
      finally:
          os.close(parent_fd)

      info = os.fstat(log_fd)
      if not stat.S_ISREG(info.st_mode) or info.st_nlink != 1 or info.st_uid != os.geteuid():
          os.close(log_fd)
          raise RuntimeError("log path must be a singly-linked regular file owned by the VM user")
      os.fchmod(log_fd, 0o600)

      journal = subprocess.Popen(
          ["/usr/bin/journalctl", "-kf", "-o", "short-iso"],
          stdout=subprocess.PIPE,
          bufsize=0,
      )
      assert journal.stdout is not None
      for line in journal.stdout:
          if b"watermelon-net " not in line:
              continue
          if os.fstat(log_fd).st_size + len(line) > max_log_bytes:
              # Rotate in place so host-side clear/read operations and this
              # long-lived verified descriptor continue to share one inode.
              os.ftruncate(log_fd, 0)
          view = memoryview(line)
          while view:
              written = os.write(log_fd, view)
              view = view[written:]
      os.close(log_fd)
      sys.exit(journal.wait())
      LOGWRITER
      /bin/chown root:root "$_WM_LOG_WRITER_TMP"
      /bin/chmod 0755 "$_WM_LOG_WRITER_TMP"
      /bin/mv -f "$_WM_LOG_WRITER_TMP" /usr/local/libexec/watermelon/log-writer
      cat > /etc/systemd/system/watermelon-log-writer.service << 'LOGSERVICE'
      [Unit]
      Description=Watermelon firewall log writer
      After=network.target

      [Service]
      User={{ .VMUser }}
      Group={{ .VMUser }}
      SupplementaryGroups=systemd-journal
      ExecStart=/usr/local/libexec/watermelon/log-writer
      Restart=always
      RestartSec=1

      [Install]
      WantedBy=multi-user.target
      LOGSERVICE
      systemctl daemon-reload
      systemctl enable watermelon-log-writer.service
      fi
      systemctl restart watermelon-log-writer.service
{{- end }}
{{- if .GlobalWildcardRules }}
      # Global ipset for wildcard domains resolved via dnsmasq
      ipset create watermelon-global-allow hash:ip -exist
      ipset flush watermelon-global-allow
{{- end }}

      # Managed host DNS. Fail/silent modes forward only configured names;
      # log/ask forward every name for discovery and interactive prompting.
      mkdir -p /etc/watermelon
      cat > /etc/watermelon/dns.conf << 'DNSCONF'
      port=5354
      bind-interfaces
      listen-address=127.0.0.1
      no-resolv
      user=watermelon-dns
      group=watermelon-dns
      pid-file=/run/watermelon-dns.pid
{{- if .DNSAllowlistOnly }}
      no-hosts
      addn-hosts=/etc/watermelon/allowed-hosts
{{- range .DNSWildcardHosts }}
      server=/*.{{ . }}/8.8.8.8
      server=/*.{{ . }}/8.8.4.4
{{- end }}
      # Names outside the policy are answered locally with NXDOMAIN.
      address=/#/
{{- else }}
{{- if .RejectUnknown }}
      addn-hosts=/etc/watermelon/allowed-hosts
{{- end }}
      server=8.8.8.8
      server=8.8.4.4
{{- end }}
{{- range .GlobalWildcardRules }}
      ipset=/*.{{ .Host }}/watermelon-global-allow
{{- end }}
      DNSCONF
      cat > /etc/systemd/system/watermelon-dns.service << 'DNSSERVICE'
      [Unit]
      Description=Watermelon managed DNS resolver

      [Service]
      ExecStart=/usr/sbin/dnsmasq --keep-in-foreground --conf-file=/etc/watermelon/dns.conf
      Restart=always
      RestartSec=1
      DNSSERVICE
      systemctl daemon-reload
      systemctl disable watermelon-dns.service 2>/dev/null || true
      systemctl restart watermelon-dns.service

      # Route host-namespace DNS through the managed resolver.
      mkdir -p /etc/systemd/resolved.conf.d
      cat > /etc/systemd/resolved.conf.d/watermelon.conf << 'RESOLVEDCONF'
      [Resolve]
      DNS=127.0.0.1:5354
      FallbackDNS=
      Domains=~.
      RESOLVEDCONF
      systemctl restart systemd-resolved
      # Network restrictions via iptables
      # Only the managed resolver may reach external DNS. Redirect direct
      # workload DNS to it, then reject any port-53 traffic that escapes NAT.
      iptables -w -t nat -N WM_DNS_OUT
      iptables -w -N WM_OUTPUT
      iptables -w -t nat -A WM_DNS_OUT -p tcp --dport 53 -m owner ! --uid-owner "$_WM_DNS_UID" -j REDIRECT --to-ports 5354
      iptables -w -t nat -A WM_DNS_OUT -p udp --dport 53 -m owner ! --uid-owner "$_WM_DNS_UID" -j REDIRECT --to-ports 5354
      # In the local OUTPUT path, REDIRECT updates the destination and port
      # before filter evaluation, but Linux does not recalculate the output
      # interface until after that hook finishes. Admit the translated packet
      # by its loopback destination instead of relying only on "-o lo".
      iptables -w -A WM_OUTPUT -p tcp -d 127.0.0.1 --dport 5354 -m owner ! --uid-owner "$_WM_DNS_UID" -j ACCEPT
      iptables -w -A WM_OUTPUT -p udp -d 127.0.0.1 --dport 5354 -m owner ! --uid-owner "$_WM_DNS_UID" -j ACCEPT
      iptables -w -A WM_OUTPUT -p tcp -d 8.8.8.8 --dport 53 -m owner --uid-owner "$_WM_DNS_UID" -j ACCEPT
      iptables -w -A WM_OUTPUT -p udp -d 8.8.8.8 --dport 53 -m owner --uid-owner "$_WM_DNS_UID" -j ACCEPT
      iptables -w -A WM_OUTPUT -p tcp -d 8.8.4.4 --dport 53 -m owner --uid-owner "$_WM_DNS_UID" -j ACCEPT
      iptables -w -A WM_OUTPUT -p udp -d 8.8.4.4 --dport 53 -m owner --uid-owner "$_WM_DNS_UID" -j ACCEPT
      iptables -w -A WM_OUTPUT -p tcp --dport 53 -j REJECT
      iptables -w -A WM_OUTPUT -p udp --dport 53 -j REJECT
{{- range .NetworkRules }}
{{- if not .Wildcard }}
      iptables -w -A WM_OUTPUT {{ if .Port }}-p tcp --dport {{ .Port }} {{ end }}-d {{ .Host }} -j ACCEPT
{{- end }}
{{- end }}
{{- if .GlobalWildcardRules }}
      iptables -w -A WM_OUTPUT -m set --match-set watermelon-global-allow dst -j ACCEPT
{{- end }}
      iptables -w -A WM_OUTPUT -o lo -j ACCEPT
      iptables -w -A WM_OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
      # Scope the DHCP exception so unprivileged port 68 cannot become a
      # generic UDP egress bypass. Broadcast discovery and renewal to the
      # current default gateway are the only permitted destinations.
      iptables -w -A WM_OUTPUT -p udp --sport 68 --dport 67 -d 255.255.255.255 -j ACCEPT
      _WM_DEFAULT_GW=$(/usr/sbin/ip -4 route show default | /usr/bin/awk '{ for (i = 1; i < NF; i++) if ($i == "via") { print $(i + 1); exit } }')
      if [ -n "$_WM_DEFAULT_GW" ]; then
        case "$_WM_DEFAULT_GW" in
          *[!0-9.]*)
            echo "default IPv4 gateway has an invalid address" >&2
            exit 1
            ;;
        esac
        iptables -w -A WM_OUTPUT -p udp --sport 68 --dport 67 -d "$_WM_DEFAULT_GW" -j ACCEPT
      fi
{{- if eq .Enforcement "ask" }}
      # Ask mode: queue unknown TCP SYN packets for interactive verdict
      _WM_GW=$_WM_DEFAULT_GW
      if [ -z "$_WM_GW" ]; then
        echo "ask enforcement requires an IPv4 default gateway" >&2
        exit 1
      fi
      iptables -w -A WM_OUTPUT -p tcp -d "$_WM_GW" --dport {{ .VerdictServerPort }} -m owner --uid-owner 0 -j ACCEPT
      iptables -w -A WM_OUTPUT -p tcp --syn -j NFQUEUE --queue-num 0
      # Queue inbound DNS responses for domain snooping
      iptables -w -A INPUT -p udp --sport 53 -j NFQUEUE --queue-num 1
      iptables -w -A WM_OUTPUT -j REJECT
{{- else }}
{{- if .LogUnknown }}
      iptables -w -A WM_OUTPUT -m limit --limit 30/min -j LOG --log-prefix "watermelon-net " --log-level 4
{{- end }}
{{- if .RejectUnknown }}
      iptables -w -A WM_OUTPUT -j REJECT
{{- end }}
{{- end }}
      # Publish complete chains only after every rule has been constructed.
      iptables -w -t nat -I OUTPUT 1 -j WM_DNS_OUT
      iptables -w -I OUTPUT 1 -j WM_OUTPUT
{{- if eq .Enforcement "ask" }}
      if [ "$_WM_FIRST_BOOT" = true ]; then
      # Set up NFQUEUE verdict daemon
      if [ ! -f {{ shellQuote .NfqdBinaryPath }} ] || [ -L {{ shellQuote .NfqdBinaryPath }} ]; then
        echo "watermelon-nfqd bootstrap source must be a regular, non-symlink file" >&2
        exit 1
      fi
      _WM_NFQD_OWNER=$(/usr/bin/stat -c %u -- {{ shellQuote .NfqdBinaryPath }})
      case "$_WM_NFQD_OWNER" in
        0|"$_WM_UID") ;;
        *)
          echo "watermelon-nfqd bootstrap source has an unexpected owner" >&2
          exit 1
          ;;
      esac
      _WM_NFQD_TMP=$(/usr/bin/mktemp /usr/local/libexec/watermelon/.nfqd.XXXXXX)
      /bin/cp --no-preserve=mode,ownership,timestamps -- {{ shellQuote .NfqdBinaryPath }} "$_WM_NFQD_TMP"
      _WM_NFQD_ACTUAL=$(/usr/bin/sha256sum "$_WM_NFQD_TMP" | /usr/bin/awk '{print $1}')
      if [ "$_WM_NFQD_ACTUAL" != "{{ .NfqdSHA256 }}" ]; then
        /bin/rm -f "$_WM_NFQD_TMP"
        echo "watermelon-nfqd failed integrity verification" >&2
        exit 1
      fi
      /bin/chown root:root "$_WM_NFQD_TMP"
      /bin/chmod 0755 "$_WM_NFQD_TMP"
      /bin/mv -f "$_WM_NFQD_TMP" /usr/local/libexec/watermelon/nfqd

      # Keep the shared verdict key out of argv and away from the unprivileged
      # workload user. The immutable host config provisions it directly into a
      # root-only guest file and validates that file again on every boot.
      /bin/mkdir -p /etc/watermelon
      /bin/chown root:root /etc/watermelon
      /bin/chmod 0755 /etc/watermelon
      _WM_VERDICT_KEY_TMP=$(/usr/bin/mktemp /etc/watermelon/.verdict-auth-key.XXXXXX)
      printf '%s' '{{ .VerdictAuthKey }}' > "$_WM_VERDICT_KEY_TMP"
      /bin/chown root:root "$_WM_VERDICT_KEY_TMP"
      /bin/chmod 0600 "$_WM_VERDICT_KEY_TMP"
      /bin/mv -f "$_WM_VERDICT_KEY_TMP" {{ shellQuote .VerdictAuthKeyPath }}
      _WM_GW=$_WM_DEFAULT_GW
      cat > /etc/systemd/system/watermelon-nfqd.service << NFQDEOF
      [Unit]
      Description=Watermelon NFQUEUE Verdict Daemon
      After=network.target

      [Service]
      ExecStart=/usr/local/libexec/watermelon/nfqd -server ${_WM_GW}:{{ .VerdictServerPort }} -auth-key-file {{ .VerdictAuthKeyPath }}
      Restart=on-failure
      RestartSec=1

      [Install]
      WantedBy=multi-user.target
      NFQDEOF
      systemctl daemon-reload
      systemctl enable watermelon-nfqd
      fi
      if [ ! -f {{ shellQuote .VerdictAuthKeyPath }} ] || [ -L {{ shellQuote .VerdictAuthKeyPath }} ] || [ "$(/usr/bin/stat -c %u -- {{ shellQuote .VerdictAuthKeyPath }})" != 0 ] || [ "$(/usr/bin/stat -c %a -- {{ shellQuote .VerdictAuthKeyPath }})" != 600 ] || [ "$(/usr/bin/stat -c %s -- {{ shellQuote .VerdictAuthKeyPath }})" != 64 ]; then
        echo "watermelon verdict authentication key must be a root-owned regular 0600 file containing exactly 64 bytes" >&2
        exit 1
      fi
      if [ "$(/bin/cat -- {{ shellQuote .VerdictAuthKeyPath }})" != "{{ .VerdictAuthKey }}" ]; then
        echo "watermelon verdict authentication key failed integrity verification" >&2
        exit 1
      fi
      systemctl restart watermelon-nfqd
{{- end }}
      if [ "$_WM_FIRST_BOOT" = true ]; then
        :
{{- if .ProvisionBuilds }}
      # User-configured package installation runs only after managed DNS and
      # the host OUTPUT policy are active. Host networking makes the container
      # traffic traverse that policy instead of a separate container egress path.
{{- range .ProvisionBuilds }}
      wm_nerdctl rm -f {{ .CustomTag }}-build 2>/dev/null || true
      wm_nerdctl run --name {{ .CustomTag }}-build --network=host "{{ .BaseImage }}"{{ range .InstallArgs }} {{ shellQuote . }}{{ end }}
      wm_nerdctl commit {{ .CustomTag }}-build {{ .CustomTag }}
      wm_nerdctl rm {{ .CustomTag }}-build
{{- end }}
{{- end }}
{{- if and .NetworkProcessRules .UniqueImages }}
      # Copy policy-ready images into the rootful store used by network
      # namespace wrappers. No network access is needed for save/load.
{{- range .UniqueImages }}
      wm_nerdctl save "{{ . }}" | wm_root_nerdctl load
{{- end }}
{{- end }}
{{- if .Tools }}
      # Create wrapper scripts for containerized tools.
{{- range $image, $cmds := .Tools }}
{{- range $cmd := $cmds }}
      printf '%s\n' '#!/bin/bash' 'set -euo pipefail'{{ if $.DynamicWorkdir }} '_WM_WORKDIR=$(/bin/pwd -P)' 'case "$_WM_WORKDIR" in /*) ;; *) echo "unable to resolve the guest workspace" >&2; exit 1 ;; esac'{{ end }} '# watermelon-image: {{ $image }}' 'if [ -t 0 ]; then' '    exec nerdctl run --rm -it --network=host {{ $.ContainerWorkdirArgs }} {{ $image }} {{ $cmd }} "$@"' 'else' '    exec nerdctl run --rm --network=host {{ $.ContainerWorkdirArgs }} {{ $image }} {{ $cmd }} "$@"' 'fi' > /usr/local/bin/{{ $cmd }}
      chmod +x /usr/local/bin/{{ $cmd }}
{{- end }}
{{- end }}
{{- end }}
{{- if .ProvisionBuilds }}
      # Discover and create wrapper scripts for provisioned binaries without
      # giving the inspection containers a network interface. Container output
      # is NUL-delimited and every name is validated before it is used in a path.
{{- range .ProvisionBuilds }}
      _WM_BASE_BINS_FILE=$(/usr/bin/mktemp)
      _WM_CUSTOM_BINS_FILE=$(/usr/bin/mktemp)
      wm_nerdctl run --rm --network=none "{{ .BaseImage }}" sh -c 'find {{ .BinDirs }} -mindepth 1 -maxdepth 1 \( -type f -o -type l \) -printf "%f\0" 2>/dev/null || true' | /usr/bin/sort -zu > "$_WM_BASE_BINS_FILE"
      wm_nerdctl run --rm --network=none "{{ .CustomTag }}" sh -c 'find {{ .BinDirs }} -mindepth 1 -maxdepth 1 \( -type f -o -type l \) -printf "%f\0" 2>/dev/null || true' | /usr/bin/sort -zu > "$_WM_CUSTOM_BINS_FILE"
      while IFS= read -r -d '' _bin; do
        case "$_bin" in
          ""|.|..|*[!A-Za-z0-9._+-]*)
            echo "Watermelon: ignoring unsafe provisioned executable name" >&2
            continue
            ;;
        esac
        [ -f "/usr/local/bin/$_bin" ] && continue
        printf '%s\n' '#!/bin/bash' 'set -euo pipefail'{{ if $.DynamicWorkdir }} '_WM_WORKDIR=$(/bin/pwd -P)' 'case "$_WM_WORKDIR" in /*) ;; *) echo "unable to resolve the guest workspace" >&2; exit 1 ;; esac'{{ end }} '# watermelon-image: {{ .CustomTag }}' 'if [ -t 0 ]; then' '    exec nerdctl run --rm -it --network=host {{ $.ContainerWorkdirArgs }} {{ .CustomTag }} '"$_bin"' "$@"' 'else' '    exec nerdctl run --rm --network=host {{ $.ContainerWorkdirArgs }} {{ .CustomTag }} '"$_bin"' "$@"' 'fi' > "/usr/local/bin/$_bin"
        chmod +x "/usr/local/bin/$_bin"
      done < <(/usr/bin/comm -z -13 "$_WM_BASE_BINS_FILE" "$_WM_CUSTOM_BINS_FILE")
      /bin/rm -f "$_WM_BASE_BINS_FILE" "$_WM_CUSTOM_BINS_FILE"
{{- if .ExposeBins }}
      # Ensure wrappers exist for provisioned package commands.
      for _bin in {{ join .ExposeBins " " }}; do
        [ -f "/usr/local/bin/$_bin" ] && continue
        printf '%s\n' '#!/bin/bash' 'set -euo pipefail'{{ if $.DynamicWorkdir }} '_WM_WORKDIR=$(/bin/pwd -P)' 'case "$_WM_WORKDIR" in /*) ;; *) echo "unable to resolve the guest workspace" >&2; exit 1 ;; esac'{{ end }} '# watermelon-image: {{ .CustomTag }}' 'if [ -t 0 ]; then' '    exec nerdctl run --rm -it --network=host {{ $.ContainerWorkdirArgs }} {{ .CustomTag }} '"$_bin"' "$@"' 'else' '    exec nerdctl run --rm --network=host {{ $.ContainerWorkdirArgs }} {{ .CustomTag }} '"$_bin"' "$@"' 'fi' > "/usr/local/bin/$_bin"
        chmod +x "/usr/local/bin/$_bin"
      done
{{- end }}
{{- end }}
{{- end }}
{{- range .SmartWrappers }}
      # Smart {{ .Cmd }} wrapper: persists global installs via nerdctl commit.
      cat > /usr/local/bin/{{ .Cmd }} << 'WATERMELON_SMART_WRAPPER_{{ .Cmd }}'
      #!/bin/bash
      # watermelon-image: {{ .CustomTag }}
{{ if $.DynamicWorkdir }}
      _WM_WORKDIR=$(/bin/pwd -P)
      case "$_WM_WORKDIR" in
        /*) ;;
        *) echo "unable to resolve the guest workspace" >&2; exit 1 ;;
      esac
{{ end }}
      # Base images are pulled during trusted bootstrap; never pull lazily here.
      if ! nerdctl image inspect "{{ .CustomTag }}" >/dev/null 2>&1; then
        if ! nerdctl image inspect "{{ .BaseImage }}" >/dev/null 2>&1; then
          echo "Watermelon base image {{ .BaseImage }} is missing; recreate the sandbox" >&2
          exit 1
        fi
        nerdctl tag "{{ .BaseImage }}" "{{ .CustomTag }}"
      fi

      # Detect global install
      _wm_global=false
{{ indent 6 .GlobalCheck }}

      if [ "$_wm_global" = true ]; then
        # Global install: run in named container, then commit to persist.
        nerdctl rm -f {{ .CustomTag }}-adhoc 2>/dev/null || true
        if [ -t 0 ]; then
          nerdctl run --name {{ .CustomTag }}-adhoc -it --network=host {{ $.ContainerWorkdirArgs }} "{{ .CustomTag }}" {{ .Cmd }} "$@"
        else
          nerdctl run --name {{ .CustomTag }}-adhoc --network=host {{ $.ContainerWorkdirArgs }} "{{ .CustomTag }}" {{ .Cmd }} "$@"
        fi
        _wm_exit=$?
        if [ $_wm_exit -eq 0 ]; then
          nerdctl commit {{ .CustomTag }}-adhoc "{{ .CustomTag }}" >/dev/null
          nerdctl rm {{ .CustomTag }}-adhoc >/dev/null
          echo "Watermelon: newly installed executables are not exposed automatically; invoke them through {{ .Cmd }}, or add them to [provision] and recreate the sandbox." >&2
        else
          nerdctl rm -f {{ .CustomTag }}-adhoc 2>/dev/null || true
        fi
        exit $_wm_exit
      else
        # Regular {{ .Cmd }} command: ephemeral container.
        if [ -t 0 ]; then
          exec nerdctl run --rm -it --network=host {{ $.ContainerWorkdirArgs }} "{{ .CustomTag }}" {{ .Cmd }} "$@"
        else
          exec nerdctl run --rm --network=host {{ $.ContainerWorkdirArgs }} "{{ .CustomTag }}" {{ .Cmd }} "$@"
        fi
      fi
      WATERMELON_SMART_WRAPPER_{{ .Cmd }}
      chmod +x /usr/local/bin/{{ .Cmd }}
{{- end }}
      fi
{{- if .NetworkProcessRules }}
      # Per-process network namespaces
{{- $netIndex := 1 }}
{{- range $proc := .SortedProcessNames }}
{{- $domains := index $.NetworkProcessRules $proc }}
{{- $kernelID := index $.ProcessKernelIDs $proc }}
      # Setup namespace for {{ $proc }}
      ip netns add wmns-{{ $kernelID }}

      # Create veth pair
      ip link add wh-{{ $kernelID }} type veth peer name wn-{{ $kernelID }}
      ip link set wn-{{ $kernelID }} netns wmns-{{ $kernelID }}

      # Configure host side
      ip addr add 10.200.{{ $netIndex }}.1/24 dev wh-{{ $kernelID }}
      ip link set wh-{{ $kernelID }} up

      # Configure namespace side
      ip netns exec wmns-{{ $kernelID }} ip addr add 10.200.{{ $netIndex }}.2/24 dev wn-{{ $kernelID }}
      ip netns exec wmns-{{ $kernelID }} ip link set wn-{{ $kernelID }} up
      ip netns exec wmns-{{ $kernelID }} ip link set lo up
      ip netns exec wmns-{{ $kernelID }} ip route add default via 10.200.{{ $netIndex }}.1

      # Enable forwarding and NAT for this namespace
      iptables -w -t nat -A POSTROUTING -s 10.200.{{ $netIndex }}.0/24 -j MASQUERADE
      echo 1 > /proc/sys/net/ipv4/ip_forward

      # Create ipset for wildcard domains in ROOT namespace (ipset + nf_tables
      # don't work together inside network namespaces on Ubuntu 22.04)
      ipset create wm-{{ $kernelID }}-allow hash:ip -exist
      ipset flush wm-{{ $kernelID }}-allow

      # Configure a managed resolver for {{ $proc }}.
      # Runs in ROOT namespace on the host side of the veth (10.200.{{ $netIndex }}.1).
      # In fail/silent modes it forwards only global and process allow rules.
      mkdir -p /etc/watermelon
      cat > /etc/watermelon/process-{{ $kernelID }}-dns.conf << 'DNSCONF'
      # dnsmasq config for {{ $proc }}
      port=53
      bind-interfaces
      listen-address=10.200.{{ $netIndex }}.1
      no-resolv
      user=watermelon-dns
      group=watermelon-dns
      pid-file=/run/watermelon-process-{{ $kernelID }}-dns.pid
{{- if $.DNSAllowlistOnly }}
      no-hosts
      addn-hosts=/etc/watermelon/process-{{ $kernelID }}-allowed-hosts
{{- $wildcardHosts := index $.ProcessDNSWildcards $proc }}
{{- range $wildcardHosts }}
      server=/*.{{ . }}/8.8.8.8
      server=/*.{{ . }}/8.8.4.4
{{- end }}
      address=/#/
{{- else }}
{{- if $.RejectUnknown }}
      addn-hosts=/etc/watermelon/process-{{ $kernelID }}-allowed-hosts
{{- end }}
      server=8.8.8.8
      server=8.8.4.4
{{- end }}
{{- range $domains }}
{{- if .Wildcard }}
      ipset=/*.{{ .Host }}/wm-{{ $kernelID }}-allow
{{- end }}
{{- end }}
{{- range $.GlobalWildcardRules }}
      ipset=/*.{{ .Host }}/wm-{{ $kernelID }}-allow
{{- end }}
      DNSCONF
      dnsmasq --conf-file=/etc/watermelon/process-{{ $kernelID }}-dns.conf
      mkdir -p /etc/netns/wmns-{{ $kernelID }}
      echo "nameserver 10.200.{{ $netIndex }}.1" > /etc/netns/wmns-{{ $kernelID }}/resolv.conf

      # Filter traffic in root FORWARD chain (where ipset works correctly).
      # Create a per-process chain for clean separation.
      # Redirect attempts to use an arbitrary resolver back to the managed one.
      iptables -w -t nat -A PREROUTING -i wh-{{ $kernelID }} -p tcp --dport 53 -j DNAT --to-destination 10.200.{{ $netIndex }}.1:53
      iptables -w -t nat -A PREROUTING -i wh-{{ $kernelID }} -p udp --dport 53 -j DNAT --to-destination 10.200.{{ $netIndex }}.1:53
      iptables -w -N WMF_{{ $kernelID }}
      iptables -w -A WMF_{{ $kernelID }} -p tcp -d 10.200.{{ $netIndex }}.1 --dport 53 -j ACCEPT
      iptables -w -A WMF_{{ $kernelID }} -p udp -d 10.200.{{ $netIndex }}.1 --dport 53 -j ACCEPT
      iptables -w -A WMF_{{ $kernelID }} -m set --match-set wm-{{ $kernelID }}-allow dst -j ACCEPT
{{- range $.NetworkRules }}
{{- if not .Wildcard }}
      iptables -w -A WMF_{{ $kernelID }} {{ if .Port }}-p tcp --dport {{ .Port }} {{ end }}-d {{ .Host }} -j ACCEPT
{{- end }}
{{- end }}
{{- range $domains }}
{{- if not .Wildcard }}
      iptables -w -A WMF_{{ $kernelID }} {{ if .Port }}-p tcp --dport {{ .Port }} {{ end }}-d {{ .Host }} -j ACCEPT
{{- end }}
{{- end }}
{{- if $.LogUnknown }}
      iptables -w -A WMF_{{ $kernelID }} -m limit --limit 30/min -j LOG --log-prefix "watermelon-net " --log-level 4
{{- end }}
{{- if eq $.Enforcement "ask" }}
      iptables -w -A WMF_{{ $kernelID }} -p tcp --syn -j NFQUEUE --queue-num 0
{{- end }}
{{- if $.RejectUnknown }}
      iptables -w -A WMF_{{ $kernelID }} -j REJECT
{{- end }}
      # Route outbound traffic from this namespace through the filter chain;
      # allow return traffic unconditionally.
      iptables -w -I FORWARD 1 -i wh-{{ $kernelID }} -j WMF_{{ $kernelID }}
      iptables -w -I FORWARD 1 -o wh-{{ $kernelID }} -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

{{- $procImage := index $.NetworkProcessImages $proc }}
      # Reassert a root-owned fixed launcher on every boot. The public wrapper
      # can only sudo this exact path; all runtime-affecting values other than
      # arguments to the configured process are baked into the launcher.
{{- if $.BootstrapImages }}
      _WM_PROC_IMAGE="{{ $procImage }}"
      _WM_PROC_IMAGE_STATE=/var/lib/watermelon/process-{{ $kernelID }}-image
      if [ -z "$_WM_PROC_IMAGE" ] && [ -f "$_WM_PROC_IMAGE_STATE" ] && [ ! -L "$_WM_PROC_IMAGE_STATE" ] && [ "$(/usr/bin/stat -c %u "$_WM_PROC_IMAGE_STATE")" = 0 ] && [ "$(/usr/bin/stat -c %a "$_WM_PROC_IMAGE_STATE")" = 600 ]; then
        IFS= read -r _WM_PROC_IMAGE < "$_WM_PROC_IMAGE_STATE" || true
      fi
      if [ -z "$_WM_PROC_IMAGE" ] && [ -f "/usr/local/bin/{{ $proc }}" ]; then
        _WM_PROC_IMAGE=$(/usr/bin/awk '$1 == "#" && $2 == "watermelon-image:" { print $3; exit }' "/usr/local/bin/{{ $proc }}")
      fi
      case "$_WM_PROC_IMAGE" in
        *[!A-Za-z0-9._/@:+-]*) _WM_PROC_IMAGE="" ;;
      esac
      if [ -n "$_WM_PROC_IMAGE" ]; then
        _WM_IMAGE_STATE_TMP=$(/usr/bin/mktemp /var/lib/watermelon/.process-{{ $kernelID }}-image.XXXXXX)
        /usr/bin/printf '%s\n' "$_WM_PROC_IMAGE" > "$_WM_IMAGE_STATE_TMP"
        /bin/chown root:root "$_WM_IMAGE_STATE_TMP"
        /bin/chmod 0600 "$_WM_IMAGE_STATE_TMP"
        /bin/mv -f "$_WM_IMAGE_STATE_TMP" "$_WM_PROC_IMAGE_STATE"

        _WM_HELPER_TMP=$(/usr/bin/mktemp /usr/local/libexec/watermelon/.process-{{ $kernelID }}.XXXXXX)
        /bin/cat > "$_WM_HELPER_TMP" << CONTAINERHELPER
      #!/bin/bash -p
      set -euo pipefail
{{- if $.DynamicWorkdir }}
      _WM_WORKDIR=\$(/bin/pwd -P)
      case "\$_WM_WORKDIR" in
        /*) ;;
        *) echo "unable to resolve the guest workspace" >&2; exit 1 ;;
      esac
{{- end }}
      if [ -t 0 ]; then
        exec /usr/bin/env -i HOME=/var/empty XDG_CONFIG_HOME=/var/empty PATH=/usr/sbin:/usr/bin:/sbin:/bin \
          /usr/local/libexec/watermelon/nerdctl --address /run/containerd/containerd.sock --namespace default \
          run --rm -it --pull=never --network=ns:/var/run/netns/wmns-{{ $kernelID }} --dns 10.200.{{ $netIndex }}.1 \
          --user $_WM_UID:$_WM_GID --cap-drop=ALL --security-opt=no-new-privileges \
          --env HOME=/tmp --env USER=$_WM_USER --env LOGNAME=$_WM_USER \
          {{ $.HelperWorkdirArgs }} -- "$_WM_PROC_IMAGE" "{{ $proc }}" "\$@"
      else
        exec /usr/bin/env -i HOME=/var/empty XDG_CONFIG_HOME=/var/empty PATH=/usr/sbin:/usr/bin:/sbin:/bin \
          /usr/local/libexec/watermelon/nerdctl --address /run/containerd/containerd.sock --namespace default \
          run --rm --pull=never --network=ns:/var/run/netns/wmns-{{ $kernelID }} --dns 10.200.{{ $netIndex }}.1 \
          --user $_WM_UID:$_WM_GID --cap-drop=ALL --security-opt=no-new-privileges \
          --env HOME=/tmp --env USER=$_WM_USER --env LOGNAME=$_WM_USER \
          {{ $.HelperWorkdirArgs }} -- "$_WM_PROC_IMAGE" "{{ $proc }}" "\$@"
      fi
      CONTAINERHELPER
        /bin/chown root:root "$_WM_HELPER_TMP"
        /bin/chmod 0755 "$_WM_HELPER_TMP"
        /bin/mv -f "$_WM_HELPER_TMP" /usr/local/libexec/watermelon/process-{{ $kernelID }}
      else
{{- end }}
        # A native command enters the fixed namespace as root, then setpriv
        # irreversibly drops to the Lima UID/GID with no new privileges or caps.
        _WM_NATIVE_BACKUP=/usr/local/libexec/watermelon/native-{{ $kernelID }}
        _WM_REAL_BIN=""
        if [ -f "$_WM_NATIVE_BACKUP" ] && [ ! -L "$_WM_NATIVE_BACKUP" ] && [ -x "$_WM_NATIVE_BACKUP" ] && [ "$(/usr/bin/stat -c %u "$_WM_NATIVE_BACKUP")" = 0 ]; then
          _WM_REAL_BIN=$_WM_NATIVE_BACKUP
        else
          while IFS= read -r _WM_CANDIDATE; do
            [ "$_WM_CANDIDATE" = "/usr/local/bin/{{ $proc }}" ] && continue
            _WM_CANDIDATE=$(/usr/bin/readlink -f -- "$_WM_CANDIDATE")
            if [ -f "$_WM_CANDIDATE" ] && [ -x "$_WM_CANDIDATE" ]; then
              _WM_REAL_BIN=$_WM_CANDIDATE
              break
            fi
          done < <(type -aP -- "{{ $proc }}" 2>/dev/null || true)
          # If the command itself occupies the wrapper path, preserve a fixed
          # root-owned copy before atomically replacing that path.
          if [ -z "$_WM_REAL_BIN" ] && [ -f "/usr/local/bin/{{ $proc }}" ] && [ ! -L "/usr/local/bin/{{ $proc }}" ] && [ -x "/usr/local/bin/{{ $proc }}" ]; then
            /usr/bin/install -o root -g root -m 0755 "/usr/local/bin/{{ $proc }}" "$_WM_NATIVE_BACKUP"
            _WM_REAL_BIN=$_WM_NATIVE_BACKUP
          fi
        fi
        if [ -z "$_WM_REAL_BIN" ]; then
          echo "configured network process {{ $proc }} was not found in the trusted PATH" >&2
          exit 1
        fi
        printf -v _WM_REAL_BIN_Q '%q' "$_WM_REAL_BIN"
        printf -v _WM_HOME_Q '%q' "$_WM_HOME"
        printf -v _WM_USER_Q '%q' "$_WM_USER"
        _WM_HELPER_TMP=$(/usr/bin/mktemp /usr/local/libexec/watermelon/.process-{{ $kernelID }}.XXXXXX)
        /bin/cat > "$_WM_HELPER_TMP" << NATIVEHELPER
      #!/bin/bash -p
      set -euo pipefail
      exec /usr/sbin/ip netns exec wmns-{{ $kernelID }} \
        /usr/bin/setpriv --reuid=$_WM_UID --regid=$_WM_GID --init-groups \
          --no-new-privs --inh-caps=-all --ambient-caps=-all --bounding-set=-all -- \
        /usr/bin/env -i HOME=${_WM_HOME_Q} USER=${_WM_USER_Q} LOGNAME=${_WM_USER_Q} \
          PATH=/usr/local/bin:/usr/bin:/bin ${_WM_REAL_BIN_Q} "\$@"
      NATIVEHELPER
        /bin/chown root:root "$_WM_HELPER_TMP"
        /bin/chmod 0755 "$_WM_HELPER_TMP"
        /bin/mv -f "$_WM_HELPER_TMP" /usr/local/libexec/watermelon/process-{{ $kernelID }}
{{- if $.BootstrapImages }}
      fi
{{- end }}

      _WM_WRAPPER_TMP=$(/usr/bin/mktemp /usr/local/bin/.watermelon-{{ $kernelID }}.XXXXXX)
      /bin/cat > "$_WM_WRAPPER_TMP" << 'USERWRAPPER'
      #!/bin/sh
      exec /usr/bin/sudo -n -- /usr/local/libexec/watermelon/process-{{ $kernelID }} "$@"
      USERWRAPPER
      /bin/chown root:root "$_WM_WRAPPER_TMP"
      /bin/chmod 0755 "$_WM_WRAPPER_TMP"
      /bin/mv -f "$_WM_WRAPPER_TMP" /usr/local/bin/{{ $proc }}
{{- $netIndex = add $netIndex 1 }}
{{- end }}
{{- end }}
      # Validate the complete sudoers policy only after all fixed helpers exist,
      # and before publishing either completion marker.
      /usr/sbin/visudo -cf /etc/sudoers
      if [ "$_WM_FIRST_BOOT" = true ]; then
        mkdir -p /var/lib/watermelon
        touch /var/lib/watermelon/bootstrap-complete
      fi
      touch /run/watermelon-policy-applied

{{- range .ProvisionScripts }}
  # Configured provision scripts must be idempotent: Lima may run provisions again.
  # Execute the exact audited bytes as a child payload so a successful exit
  # still returns to this wrapper and publishes the stage marker, while any
  # non-zero result leaves the stage unmarked.
  - mode: system
    script: |
      #!/bin/bash
      set -euo pipefail
      export PATH=/usr/sbin:/usr/bin:/sbin:/bin
      # Ubuntu mounts /run with noexec, so keep only attestation markers there
      # and stage the executable payload in Watermelon's root-owned helper dir.
      _WM_PAYLOAD=$(/usr/bin/mktemp /usr/local/libexec/watermelon/.provision-{{ .Name }}.XXXXXX)
      wm_cleanup_provision_payload() {
        /bin/rm -f -- "$_WM_PAYLOAD"
      }
      trap wm_cleanup_provision_payload EXIT
      /usr/bin/base64 --decode > "$_WM_PAYLOAD" <<'WATERMELON_PROVISION_PAYLOAD'
{{ indent 6 .Base64 }}
      WATERMELON_PROVISION_PAYLOAD
      /bin/chown root:root "$_WM_PAYLOAD"
      /bin/chmod 0700 "$_WM_PAYLOAD"
      "$_WM_PAYLOAD"
      wm_cleanup_provision_payload
      trap - EXIT
      /usr/bin/install -o root -g root -m 0600 /dev/null /run/watermelon-provisioning/{{ .Name }}.complete
{{- end }}

{{- if .Workdir }}
  # Lima executes all system provisions before all user provisions regardless
  # of their YAML order. Keep this generated user-home change in the system
  # sequence so the final root-owned marker attests it as well.
  - mode: system
    script: |
      #!/bin/bash
      set -euo pipefail
      export PATH=/usr/sbin:/usr/bin:/sbin:/bin
      _WM_UID=$(/usr/bin/id -u {{ .VMUser }})
      _WM_GID=$(/usr/bin/id -g {{ .VMUser }})
      _WM_BASHRC={{ .VMUserHome }}/.bashrc
      if [ -e "$_WM_BASHRC" ] || [ -L "$_WM_BASHRC" ]; then
        if [ ! -f "$_WM_BASHRC" ] || [ -L "$_WM_BASHRC" ] || [ "$(/usr/bin/stat -c %u "$_WM_BASHRC")" != "$_WM_UID" ]; then
          echo "Watermelon: refusing unsafe $_WM_BASHRC" >&2
          exit 1
        fi
      else
        /usr/bin/install -o "$_WM_UID" -g "$_WM_GID" -m 0644 /dev/null "$_WM_BASHRC"
      fi
{{- if eq .Workdir "/project" }}
      _WM_WORKDIR_LINE='[ -d /project ] && cd /project'
{{- else }}
      _WM_WORKDIR_LINE={{ shellQuote (printf "[ -d %s ] && cd %s" (shellQuote .Workdir) (shellQuote .Workdir)) }}
{{- end }}
      if ! /usr/bin/grep -Fqx -- "$_WM_WORKDIR_LINE" "$_WM_BASHRC" 2>/dev/null; then
        /usr/bin/printf '%s\n' "$_WM_WORKDIR_LINE" >> "$_WM_BASHRC"
      fi
      /usr/bin/install -o root -g root -m 0600 /dev/null /run/watermelon-provisioning/workdir.complete
{{- end }}

  # Lima's own ready signal does not prove its provision scripts succeeded.
  # Publish Watermelon's marker only after every generated stage has left a
  # root-owned success marker in this boot's root-only runtime directory.
  - mode: system
    script: |
      #!/bin/bash
      set -euo pipefail
      export PATH=/usr/sbin:/usr/bin:/sbin:/bin
      wm_require_provision_stage() {
        _wm_stage="$1"
        if [ ! -f "$_wm_stage" ] || [ -L "$_wm_stage" ] || [ "$(/usr/bin/stat -c %u "$_wm_stage" 2>/dev/null)" != 0 ]; then
          echo "Watermelon provisioning stage did not complete: $_wm_stage" >&2
          exit 1
        fi
      }
      wm_require_provision_stage /run/watermelon-policy-applied
{{- range .ProvisionScripts }}
      wm_require_provision_stage /run/watermelon-provisioning/{{ .Name }}.complete
{{- end }}
{{- if .Workdir }}
      wm_require_provision_stage /run/watermelon-provisioning/workdir.complete
{{- end }}
      /usr/bin/install -o root -g root -m 0600 /dev/null /run/watermelon-provisioning-complete

networks: []

portForwards:
{{- range .PortForwards }}
  - guestPort: {{ . }}
    hostPort: {{ . }}
{{- end }}
  # Disable automatic port forwarding for security isolation
  - ignore: true
    guestIP: "0.0.0.0"
    guestPortRange: [1, 65535]
  - ignore: true
    guestIP: "127.0.0.1"
    guestPortRange: [1, 65535]
`

type provisionBuild struct {
	BaseImage   string
	CustomTag   string
	InstallArgs []string
	BinDirs     string
	ExposeBins  []string
}

type smartWrapper struct {
	Cmd         string // "npm", "pip", etc.
	BaseImage   string // original container image
	CustomTag   string // "watermelon-npm", etc.
	BinDirs     string // dirs to scan for new binaries
	GlobalCheck string // shell snippet setting _wm_global=true
}

type provisionScript struct {
	Name   string
	Base64 string
}

type mountData struct {
	Location string
	Target   string
	Writable bool
}

type templateData struct {
	MinimumLimaVersion   string
	VMType               string
	VMUser               string
	VMUserUID            uint32
	VMUserHome           string
	CPUs                 int
	Memory               string
	Disk                 string
	Image                string
	MountProject         bool
	ProjectDir           string
	Workdir              string
	DynamicWorkdir       bool
	ContainerWorkdirArgs string
	HelperWorkdirArgs    string
	BootstrapHostDir     string
	LogHostDir           string
	LogDir               string
	LogPath              string
	LogInGuest           bool
	Mounts               []mountData
	NetworkRules         []config.NetworkRule
	NetworkProcessRules  map[string][]config.NetworkRule
	NetworkProcessImages map[string]string // process name → container image (when known at config time)
	ProcessKernelIDs     map[string]string // process name → short stable identifier for kernel objects
	PortForwards         []int
	Tools                map[string][]string
	BootstrapImages      []string
	ProvisionBuilds      []provisionBuild
	SmartWrappers        []smartWrapper
	SortedProcessNames   []string // process names sorted alphabetically
	UniqueImages         []string // all container images that need to be in rootful store
	Enforcement          string
	LogUnknown           bool
	RejectUnknown        bool
	VerdictServerPort    int
	VerdictAuthKey       string
	VerdictAuthKeyPath   string
	NfqdBinaryPath       string
	NfqdSHA256           string
	GlobalWildcardRules  []config.NetworkRule // wildcard domains from NetworkRules
	DNSExactHosts        []string
	DNSWildcardHosts     []string
	ProcessDNSExactHosts map[string][]string
	ProcessDNSWildcards  map[string][]string
	DNSAllowlistOnly     bool
	ProvisionScripts     []provisionScript
}

var (
	hostGOOS         = runtime.GOOS
	hostEffectiveUID = func() int64 { return int64(os.Geteuid()) }
)

const (
	maxProvisionScriptSize  = 1 << 20
	maxProvisionScriptsSize = 4 << 20
	nfqdGuestDir            = "/mnt/watermelon/bootstrap"
	logStateGuestDir        = "/mnt/watermelon/state"
	verdictAuthKeyGuestPath = "/etc/watermelon/verdict-auth-key"
)

// PreparedProvisionScripts binds the exact host bytes embedded into a Lima
// config to their ordered SHA-256 digests. The CLI carries this single read
// through generation, identity reservation, and applied-policy snapshots.
type PreparedProvisionScripts struct {
	Contents []string
	SHA256   []string
}

// PrepareProvisionScripts opens configured scripts beneath a real project
// directory without following any symlink component or blocking on a special
// file. Scripts run as root in the VM and Lima may retry them, so callers must
// author them to be idempotent.
func PrepareProvisionScripts(projectDir string, scripts []string) (PreparedProvisionScripts, error) {
	contents := make([]string, 0, len(scripts))
	digests := make([]string, 0, len(scripts))
	if len(scripts) == 0 {
		return PreparedProvisionScripts{Contents: contents, SHA256: digests}, nil
	}
	total := 0
	canonicalProjectDir, err := filepath.EvalSymlinks(projectDir)
	if err != nil {
		return PreparedProvisionScripts{}, fmt.Errorf("resolving project directory for provision scripts: %w", err)
	}
	projectFD, err := unix.Open(canonicalProjectDir, unix.O_RDONLY|unix.O_CLOEXEC|unix.O_DIRECTORY|unix.O_NOFOLLOW, 0)
	if err != nil {
		return PreparedProvisionScripts{}, fmt.Errorf("opening project directory for provision scripts: %w", err)
	}
	defer unix.Close(projectFD)
	for _, script := range scripts {
		if err := config.ValidateProvisionScript(script); err != nil {
			return PreparedProvisionScripts{}, err
		}
		fd, err := openProvisionScriptAt(projectFD, script)
		if err != nil {
			return PreparedProvisionScripts{}, err
		}
		file := os.NewFile(uintptr(fd), filepath.Join(canonicalProjectDir, script))
		if file == nil {
			_ = unix.Close(fd)
			return PreparedProvisionScripts{}, fmt.Errorf("opening provision script %q: invalid file descriptor", script)
		}

		info, statErr := file.Stat()
		if statErr != nil {
			_ = file.Close()
			return PreparedProvisionScripts{}, fmt.Errorf("inspecting provision script %q: %w", script, statErr)
		}
		if !info.Mode().IsRegular() {
			_ = file.Close()
			return PreparedProvisionScripts{}, fmt.Errorf("provision script %q must be a regular file, got %s", script, info.Mode().Type())
		}
		stat, ok := info.Sys().(*syscall.Stat_t)
		if !ok || stat.Uid != uint32(os.Geteuid()) {
			_ = file.Close()
			return PreparedProvisionScripts{}, fmt.Errorf("provision script %q must be owned by the current user", script)
		}
		if info.Size() > maxProvisionScriptSize {
			_ = file.Close()
			return PreparedProvisionScripts{}, fmt.Errorf("provision script %q exceeds the %d-byte limit", script, maxProvisionScriptSize)
		}

		data, readErr := io.ReadAll(io.LimitReader(file, maxProvisionScriptSize+1))
		closeErr := file.Close()
		if readErr != nil {
			return PreparedProvisionScripts{}, fmt.Errorf("reading provision script %q: %w", script, readErr)
		}
		if closeErr != nil {
			return PreparedProvisionScripts{}, fmt.Errorf("closing provision script %q: %w", script, closeErr)
		}
		if len(data) > maxProvisionScriptSize {
			return PreparedProvisionScripts{}, fmt.Errorf("provision script %q exceeds the %d-byte limit", script, maxProvisionScriptSize)
		}
		if !utf8.Valid(data) {
			return PreparedProvisionScripts{}, fmt.Errorf("provision script %q must contain valid UTF-8", script)
		}
		if bytes.IndexByte(data, 0) >= 0 {
			return PreparedProvisionScripts{}, fmt.Errorf("provision script %q contains a NUL byte", script)
		}
		total += len(data)
		if total > maxProvisionScriptsSize {
			return PreparedProvisionScripts{}, fmt.Errorf("provision scripts exceed the %d-byte total limit", maxProvisionScriptsSize)
		}
		contents = append(contents, string(data))
		digest := sha256.Sum256(data)
		digests = append(digests, fmt.Sprintf("%x", digest[:]))
	}
	return PreparedProvisionScripts{Contents: contents, SHA256: digests}, nil
}

func openProvisionScriptAt(projectFD int, script string) (int, error) {
	components := strings.Split(filepath.Clean(script), string(filepath.Separator))
	dirFD := projectFD
	ownedDirFD := -1
	defer func() {
		if ownedDirFD >= 0 {
			_ = unix.Close(ownedDirFD)
		}
	}()

	for _, component := range components[:len(components)-1] {
		nextFD, err := unix.Openat(dirFD, component, unix.O_RDONLY|unix.O_CLOEXEC|unix.O_DIRECTORY|unix.O_NOFOLLOW, 0)
		if err != nil {
			return -1, fmt.Errorf("opening provision script %q directory component %q without following symlinks: %w", script, component, err)
		}
		if ownedDirFD >= 0 {
			_ = unix.Close(ownedDirFD)
		}
		ownedDirFD = nextFD
		dirFD = nextFD
	}

	fileFD, err := unix.Openat(dirFD, components[len(components)-1], unix.O_RDONLY|unix.O_CLOEXEC|unix.O_NOFOLLOW|unix.O_NONBLOCK, 0)
	if err != nil {
		return -1, fmt.Errorf("opening provision script %q without following symlinks: %w", script, err)
	}
	return fileFD, nil
}

func readProvisionScripts(projectDir string, scripts []string) ([]string, error) {
	prepared, err := PrepareProvisionScripts(projectDir, scripts)
	if err != nil {
		return nil, err
	}
	return prepared.Contents, nil
}

// GenerateOptions contains host paths and values bound to a specific Lima
// instance at creation time. BootstrapHostDir is mounted read-only at the
// fixed bootstrap path and is required with NfqdSHA256 and VerdictAuthKey in
// ask mode. It may also carry immutable instance identity in other enforcement
// modes. LogHostDir, when set, is mounted read-write at the fixed instance-state
// path.
type GenerateOptions struct {
	VerdictServerPort int
	VerdictAuthKey    string
	NfqdSHA256        string
	BootstrapHostDir  string
	// NfqdHostDir is a deprecated compatibility alias for BootstrapHostDir.
	NfqdHostDir string
	LogHostDir  string
	// PreparedProvisionScripts supplies the exact bytes already audited by the
	// CLI. The generator verifies every digest before embedding them.
	PreparedProvisionScripts *PreparedProvisionScripts
}

// GenerateConfig creates Lima YAML from watermelon config. Mount sources are
// expanded from the config for direct package callers; the CLI uses
// GenerateConfigWithMountSources so the paths it audited are exactly the paths
// recorded in Lima's immutable instance config.
func GenerateConfig(cfg *config.Config, projectDir string, verdictServerPort ...int) (string, error) {
	opts := GenerateOptions{}
	if len(verdictServerPort) > 0 {
		opts.VerdictServerPort = verdictServerPort[0]
	}
	return generateConfig(cfg, projectDir, nil, opts)
}

// GenerateConfigWithMountSources creates Lima YAML using canonical host mount
// paths keyed by their original config spelling.
func GenerateConfigWithMountSources(cfg *config.Config, projectDir string, mountSources map[string]string, verdictServerPort ...int) (string, error) {
	opts := GenerateOptions{}
	if len(verdictServerPort) > 0 {
		opts.VerdictServerPort = verdictServerPort[0]
	}
	return generateConfig(cfg, projectDir, mountSources, opts)
}

// GenerateConfigForInstance creates the immutable Lima config using canonical
// host mount sources and instance-bound security inputs.
func GenerateConfigForInstance(cfg *config.Config, projectDir string, mountSources map[string]string, opts GenerateOptions) (string, error) {
	return generateConfig(cfg, projectDir, mountSources, opts)
}

func generateConfig(cfg *config.Config, projectDir string, mountSources map[string]string, opts GenerateOptions) (string, error) {
	if err := config.Validate(cfg); err != nil {
		return "", err
	}
	toolProviders, err := config.BuildToolCommandProviders(cfg.Tools)
	if err != nil {
		return "", err
	}
	if err := validateProjectDir(projectDir); err != nil {
		return "", err
	}

	// Validate port forwards
	for _, port := range cfg.Ports.Forward {
		if err := validatePort(port); err != nil {
			return "", fmt.Errorf("invalid port forward: %w", err)
		}
	}

	networkRules, globalWildcardRules, err := buildNetworkRules(cfg.Network.Allow)
	if err != nil {
		return "", fmt.Errorf("invalid network allow domain: %w", err)
	}

	networkProcessRules := make(map[string][]config.NetworkRule)
	for processName, domains := range cfg.Network.Process {
		rules, _, err := buildNetworkRules(domains)
		if err != nil {
			return "", fmt.Errorf("invalid domain for process %q: %w", processName, err)
		}
		networkProcessRules[processName] = rules
	}

	dnsExactHosts, dnsWildcardHosts := dnsHostsForRules(networkRules)
	processDNSExactHosts := make(map[string][]string, len(networkProcessRules))
	processDNSWildcards := make(map[string][]string, len(networkProcessRules))
	for processName, rules := range networkProcessRules {
		processExact, processWildcards := dnsHostsForRules(networkRules, rules)
		processDNSExactHosts[processName] = processExact
		processDNSWildcards[processName] = processWildcards
		processOnlyExact, _ := dnsHostsForRules(rules)
		dnsExactHosts = uniqueSortedStrings(append(dnsExactHosts, processOnlyExact...))
	}

	mounts, err := buildMounts(cfg.Mounts, mountSources)
	if err != nil {
		return "", err
	}
	mountProject := config.MountProjectEnabled(&cfg.VM)
	if err := validateInternalMountTargets(mounts, mountProject); err != nil {
		return "", err
	}

	vmType, err := hostVMType(hostGOOS)
	if err != nil {
		return "", err
	}
	// Lima's writable mounts preserve host ownership. Bind the fixed guest
	// account to the effective host UID so a project owned by a non-1000 macOS
	// or Linux user remains writable from the sandbox. The account name and
	// home stay fixed and are still verified by the root provisioning script.
	hostUID := hostEffectiveUID()
	if hostUID < 0 {
		return "", fmt.Errorf("effective host UID %d is invalid", hostUID)
	}
	if hostUID == 0 {
		return "", errors.New("watermelon must run as an unprivileged host user to create a Lima VM")
	}
	// Linux and Darwin expose 32-bit uid_t values. The all-ones value represents
	// an invalid/unset identity and must not be assigned to the guest account.
	const maxVMUserUID = int64(1<<32 - 2)
	if hostUID > maxVMUserUID {
		return "", fmt.Errorf("effective host UID %d is outside the supported guest UID range 1..%d", hostUID, maxVMUserUID)
	}
	vmUserUID := uint32(hostUID)

	// Build provision data: custom images and tool image overrides
	type provSpec struct {
		pkgs        []string
		cmd         string
		installArgs []string
		tag         string
		binDirs     string
	}
	specs := []provSpec{
		{cfg.Provision.Npm, "npm", []string{"npm", "install", "-g"}, "watermelon-npm", "/usr/local/bin"},
		{cfg.Provision.Pip, "pip", []string{"pip", "install"}, "watermelon-pip", "/usr/local/bin"},
		{cfg.Provision.Cargo, "cargo", []string{"cargo", "install"}, "watermelon-cargo", "/usr/local/cargo/bin /usr/local/bin"},
		{cfg.Provision.Go, "go", []string{"go", "install"}, "watermelon-go", "/go/bin /usr/local/bin"},
		{cfg.Provision.Gem, "gem", []string{"gem", "install"}, "watermelon-gem", "/usr/local/bin"},
	}

	var provisionBuilds []provisionBuild
	imageOverrides := make(map[string]string)

	for _, spec := range specs {
		if len(spec.pkgs) == 0 {
			continue
		}
		for _, pkg := range spec.pkgs {
			if err := config.ValidatePackageName(pkg); err != nil {
				return "", fmt.Errorf("invalid %s package: %w", spec.cmd, err)
			}
		}
		img := toolProviders[spec.cmd]
		if img == "" {
			return "", fmt.Errorf("provision.%s requires %s in [tools]; add a container image that provides %s", spec.cmd, spec.cmd, spec.cmd)
		}
		exposeBins, err := provisionExposeBins(spec.cmd, spec.pkgs)
		if err != nil {
			return "", fmt.Errorf("invalid exposed %s command: %w", spec.cmd, err)
		}
		imageOverrides[img] = spec.tag
		installArgs := append([]string(nil), spec.installArgs...)
		installArgs = append(installArgs, spec.pkgs...)
		provisionBuilds = append(provisionBuilds, provisionBuild{
			BaseImage:   img,
			CustomTag:   spec.tag,
			InstallArgs: installArgs,
			BinDirs:     spec.binDirs,
			ExposeBins:  exposeBins,
		})
	}

	// Apply image overrides so tool wrappers use custom images with packages pre-installed
	tools := make(map[string][]string)
	for image, cmds := range cfg.Tools {
		if override, ok := imageOverrides[image]; ok {
			tools[override] = cmds
		} else {
			tools[image] = cmds
		}
	}

	funcMap := template.FuncMap{
		"add":        func(a, b int) int { return a + b },
		"yamlQuote":  strconv.Quote,
		"shellQuote": shellQuote,
		"indent": func(n int, s string) string {
			pad := strings.Repeat(" ", n)
			return pad + strings.ReplaceAll(s, "\n", "\n"+pad)
		},
		"join": strings.Join,
	}
	tmpl, err := template.New("lima").Funcs(funcMap).Parse(limaTemplate)
	if err != nil {
		return "", fmt.Errorf("parsing template: %w", err)
	}

	// Generate smart wrappers for package manager commands found in tools
	type wrapperSpec struct {
		cmd         string
		customTag   string
		binDirs     string
		globalCheck string
	}
	wrapperSpecs := []wrapperSpec{
		{"npm", "watermelon-npm", "/usr/local/bin",
			`for _arg in "$@"; do` + "\n" + `  case "$_arg" in -g|--global) _wm_global=true ;; esac` + "\n" + `done`},
		{"pip", "watermelon-pip", "/usr/local/bin",
			`case "$1" in install) _wm_global=true ;; esac`},
		{"cargo", "watermelon-cargo", "/usr/local/cargo/bin /usr/local/bin",
			`case "$1" in install) _wm_global=true ;; esac`},
		{"go", "watermelon-go", "/go/bin /usr/local/bin",
			`case "$1" in install) _wm_global=true ;; esac`},
		{"gem", "watermelon-gem", "/usr/local/bin",
			`case "$1" in install) _wm_global=true ;; esac`},
	}

	var smartWrappers []smartWrapper
	for _, ws := range wrapperSpecs {
		if img := toolProviders[ws.cmd]; img != "" {
			smartWrappers = append(smartWrappers, smartWrapper{
				Cmd:         ws.cmd,
				BaseImage:   img,
				CustomTag:   ws.customTag,
				BinDirs:     ws.binDirs,
				GlobalCheck: ws.globalCheck,
			})
		}
	}

	effectiveToolProviders := make(map[string]string, len(toolProviders))
	for command, image := range toolProviders {
		if override, ok := imageOverrides[image]; ok {
			effectiveToolProviders[command] = override
		} else {
			effectiveToolProviders[command] = image
		}
	}
	networkProcessImages := buildNetworkProcessImages(effectiveToolProviders, cfg.Network.Process)

	// Collect container images that need to be copied to rootful store
	// when network process namespaces are in use.
	var uniqueImages []string
	if len(networkProcessRules) > 0 {
		uniqueImages = collectUniqueImages(tools)
	}

	image := cfg.VM.Image
	if image == "" {
		image = "ubuntu-22.04"
	}
	workdir := config.DefaultWorkdir(cfg)
	containerWorkdirArgs := ""
	helperWorkdirArgs := ""
	if workdir == "" {
		containerWorkdirArgs = `-v "$_WM_WORKDIR:$_WM_WORKDIR" -w "$_WM_WORKDIR"`
		helperWorkdirArgs = `-v "\$_WM_WORKDIR:\$_WM_WORKDIR" -w "\$_WM_WORKDIR"`
	} else {
		if workdir == "/project" {
			containerWorkdirArgs = "-v /project:/project -w /project"
		} else {
			// These arguments are embedded both in generated scripts and inside
			// single-quoted printf operands that create tool wrappers. Validated
			// guest paths cannot contain a double quote, backslash, dollar, or
			// backtick, so strconv.Quote remains safe in both contexts and keeps
			// spaces within one argument.
			containerWorkdirArgs = "-v " + strconv.Quote(workdir+":"+workdir) + " -w " + strconv.Quote(workdir)
		}
		helperWorkdirArgs = containerWorkdirArgs
	}

	preparedScripts := opts.PreparedProvisionScripts
	if preparedScripts == nil {
		prepared, err := PrepareProvisionScripts(projectDir, cfg.Provision.Scripts)
		if err != nil {
			return "", err
		}
		preparedScripts = &prepared
	}
	if err := validatePreparedProvisionScripts(cfg, preparedScripts); err != nil {
		return "", err
	}
	provisionScripts := make([]provisionScript, len(preparedScripts.Contents))
	for index, content := range preparedScripts.Contents {
		provisionScripts[index] = provisionScript{
			Name:   fmt.Sprintf("script-%08d", index),
			Base64: encodeProvisionScript(content),
		}
	}

	bootstrapHostDir := opts.BootstrapHostDir
	if opts.NfqdHostDir != "" {
		if bootstrapHostDir != "" && bootstrapHostDir != opts.NfqdHostDir {
			return "", fmt.Errorf("bootstrap host directory and deprecated nfqd host directory disagree")
		}
		bootstrapHostDir = opts.NfqdHostDir
	}
	if bootstrapHostDir != "" {
		if err := validateProjectDir(bootstrapHostDir); err != nil {
			return "", fmt.Errorf("invalid bootstrap host directory: %w", err)
		}
		if hostPathsOverlap(bootstrapHostDir, projectDir) {
			return "", fmt.Errorf("bootstrap host directory must not overlap the project directory")
		}
		for _, mount := range mounts {
			if mount.Writable && hostPathsOverlap(bootstrapHostDir, mount.Location) {
				return "", fmt.Errorf("bootstrap host directory must not overlap writable mount %q", mount.Location)
			}
		}
	}

	verdictPort := 0
	verdictAuthKey := ""
	nfqdPath := ""
	nfqdSHA256 := ""
	if cfg.Security.Enforcement == "ask" {
		if opts.VerdictServerPort > 0 {
			if err := validatePort(opts.VerdictServerPort); err != nil {
				return "", fmt.Errorf("invalid verdict server port: %w", err)
			}
			verdictPort = opts.VerdictServerPort
		}
		if verdictPort == 0 {
			verdictPort = 39285 // fallback
		}
		for _, forwardedPort := range cfg.Ports.Forward {
			if verdictPort == forwardedPort {
				return "", fmt.Errorf("verdict server port %d conflicts with configured host port forward", verdictPort)
			}
		}
		if !validLowerSHA256(opts.NfqdSHA256) {
			return "", fmt.Errorf("ask enforcement requires a lowercase SHA-256 digest for watermelon-nfqd")
		}
		if !validLowerSHA256(opts.VerdictAuthKey) {
			return "", fmt.Errorf("ask enforcement requires a 32-byte lowercase hexadecimal verdict authentication key")
		}
		if bootstrapHostDir == "" {
			return "", fmt.Errorf("ask enforcement requires a dedicated watermelon-nfqd host bootstrap directory")
		}
		nfqdPath = path.Join(nfqdGuestDir, "watermelon-nfqd")
		nfqdSHA256 = opts.NfqdSHA256
		verdictAuthKey = opts.VerdictAuthKey
	} else if opts.NfqdSHA256 != "" || opts.VerdictAuthKey != "" {
		return "", fmt.Errorf("watermelon-nfqd digest and verdict authentication key are only valid with ask enforcement")
	}

	logHostDir := opts.LogHostDir
	if logHostDir != "" {
		if err := validateProjectDir(logHostDir); err != nil {
			return "", fmt.Errorf("invalid log host directory: %w", err)
		}
		if hostPathsOverlap(logHostDir, projectDir) {
			return "", fmt.Errorf("log host directory must not overlap the project directory")
		}
		if bootstrapHostDir != "" && hostPathsOverlap(logHostDir, bootstrapHostDir) {
			return "", fmt.Errorf("log host directory must not overlap the read-only watermelon-nfqd bootstrap directory")
		}
		for _, mount := range mounts {
			if hostPathsOverlap(logHostDir, mount.Location) {
				return "", fmt.Errorf("log host directory must not overlap configured mount %q", mount.Location)
			}
		}
	}
	logDir := logStateGuestDir
	logInGuest := false
	if logHostDir == "" {
		if mountProject {
			logDir = "/project/.watermelon"
		} else {
			logDir = "/var/log/watermelon"
			logInGuest = true
		}
	}
	logPath := path.Join(logDir, "logs.log")

	sortedProcessNames := make([]string, 0, len(networkProcessRules))
	for proc := range networkProcessRules {
		sortedProcessNames = append(sortedProcessNames, proc)
	}
	sort.Strings(sortedProcessNames)
	processKernelIDs, err := buildProcessKernelIDs(sortedProcessNames, processKernelID)
	if err != nil {
		return "", err
	}

	logUnknown := cfg.Security.Enforcement == "log" || cfg.Security.Enforcement == "fail"
	rejectUnknown := cfg.Security.Enforcement == "fail" || cfg.Security.Enforcement == "silent" || cfg.Security.Enforcement == "ask"

	data := templateData{
		MinimumLimaVersion:   MinimumSupportedVersion,
		VMType:               vmType,
		VMUser:               "watermelon",
		VMUserUID:            vmUserUID,
		VMUserHome:           "/home/watermelon",
		CPUs:                 cfg.Resources.CPUs,
		Memory:               convertMemory(cfg.Resources.Memory),
		Disk:                 convertDisk(cfg.Resources.Disk),
		Image:                image,
		MountProject:         mountProject,
		ProjectDir:           projectDir,
		Workdir:              workdir,
		DynamicWorkdir:       workdir == "",
		ContainerWorkdirArgs: containerWorkdirArgs,
		HelperWorkdirArgs:    helperWorkdirArgs,
		BootstrapHostDir:     bootstrapHostDir,
		LogHostDir:           logHostDir,
		LogDir:               logDir,
		LogPath:              logPath,
		LogInGuest:           logInGuest,
		Mounts:               mounts,
		NetworkRules:         networkRules,
		NetworkProcessRules:  networkProcessRules,
		NetworkProcessImages: networkProcessImages,
		ProcessKernelIDs:     processKernelIDs,
		SortedProcessNames:   sortedProcessNames,
		PortForwards:         cfg.Ports.Forward,
		Tools:                tools,
		BootstrapImages:      collectUniqueImages(cfg.Tools),
		ProvisionBuilds:      provisionBuilds,
		SmartWrappers:        smartWrappers,
		UniqueImages:         uniqueImages,
		Enforcement:          cfg.Security.Enforcement,
		LogUnknown:           logUnknown,
		RejectUnknown:        rejectUnknown,
		VerdictServerPort:    verdictPort,
		VerdictAuthKey:       verdictAuthKey,
		VerdictAuthKeyPath:   verdictAuthKeyGuestPath,
		NfqdBinaryPath:       nfqdPath,
		NfqdSHA256:           nfqdSHA256,
		GlobalWildcardRules:  globalWildcardRules,
		DNSExactHosts:        dnsExactHosts,
		DNSWildcardHosts:     dnsWildcardHosts,
		ProcessDNSExactHosts: processDNSExactHosts,
		ProcessDNSWildcards:  processDNSWildcards,
		DNSAllowlistOnly:     cfg.Security.Enforcement == "fail" || cfg.Security.Enforcement == "silent",
		ProvisionScripts:     provisionScripts,
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("executing template: %w", err)
	}

	return buf.String(), nil
}

func hostVMType(goos string) (string, error) {
	switch goos {
	case "darwin":
		return "vz", nil
	case "linux":
		return "qemu", nil
	default:
		return "", fmt.Errorf("unsupported host OS %q: watermelon supports macOS and Linux hosts", goos)
	}
}

func validateProjectDir(projectDir string) error {
	if !utf8.ValidString(projectDir) {
		return fmt.Errorf("project directory must be valid UTF-8")
	}
	if strings.IndexByte(projectDir, 0) >= 0 {
		return fmt.Errorf("project directory contains a NUL byte")
	}
	if !filepath.IsAbs(projectDir) {
		return fmt.Errorf("project directory %q must be absolute", projectDir)
	}
	if filepath.Clean(projectDir) != projectDir {
		return fmt.Errorf("project directory %q must be a clean path", projectDir)
	}
	return nil
}

func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", `'"'"'`) + "'"
}

// encodeProvisionScript keeps the exact audited script bytes out of both the
// Watermelon and Lima template languages. The generated wrapper decodes the
// payload into a root-only per-boot path before executing it.
func encodeProvisionScript(value string) string {
	encoded := base64.StdEncoding.EncodeToString([]byte(value))
	const lineWidth = 76
	if len(encoded) <= lineWidth {
		return encoded
	}
	var lines []string
	for len(encoded) > lineWidth {
		lines = append(lines, encoded[:lineWidth])
		encoded = encoded[lineWidth:]
	}
	if encoded != "" {
		lines = append(lines, encoded)
	}
	return strings.Join(lines, "\n")
}

func validatePreparedProvisionScripts(cfg *config.Config, prepared *PreparedProvisionScripts) error {
	if prepared == nil {
		return errors.New("prepared provision scripts cannot be nil")
	}
	if len(prepared.Contents) != len(cfg.Provision.Scripts) || len(prepared.SHA256) != len(cfg.Provision.Scripts) {
		return fmt.Errorf("prepared provision script count does not match configured scripts")
	}
	total := 0
	for index, content := range prepared.Contents {
		data := []byte(content)
		if len(data) > maxProvisionScriptSize {
			return fmt.Errorf("prepared provision script %q exceeds the %d-byte limit", cfg.Provision.Scripts[index], maxProvisionScriptSize)
		}
		if !utf8.Valid(data) || bytes.IndexByte(data, 0) >= 0 {
			return fmt.Errorf("prepared provision script %q is not valid NUL-free UTF-8", cfg.Provision.Scripts[index])
		}
		total += len(data)
		if total > maxProvisionScriptsSize {
			return fmt.Errorf("prepared provision scripts exceed the %d-byte total limit", maxProvisionScriptsSize)
		}
		digest := sha256.Sum256(data)
		actual := fmt.Sprintf("%x", digest[:])
		if prepared.SHA256[index] != actual {
			return fmt.Errorf("prepared provision script %q does not match its SHA-256 digest", cfg.Provision.Scripts[index])
		}
		if len(cfg.Provision.ScriptSHA256) != 0 && cfg.Provision.ScriptSHA256[index] != actual {
			return fmt.Errorf("prepared provision script %q does not match the applied configuration digest", cfg.Provision.Scripts[index])
		}
	}
	return nil
}

func validateInternalMountTargets(mounts []mountData, mountProject bool) error {
	for _, mount := range mounts {
		if mountProject && path.Clean(mount.Target) == "/project" {
			return fmt.Errorf("mount target %q duplicates Watermelon's project mount", mount.Target)
		}
		for _, internal := range []string{nfqdGuestDir, logStateGuestDir} {
			if guestPathsOverlap(mount.Target, internal) {
				return fmt.Errorf("mount target %q overlaps Watermelon-managed guest path %q", mount.Target, internal)
			}
		}
	}
	return nil
}

func guestPathsOverlap(first, second string) bool {
	first = path.Clean(first)
	second = path.Clean(second)
	return first == second || strings.HasPrefix(first, second+"/") || strings.HasPrefix(second, first+"/")
}

func hostPathsOverlap(first, second string) bool {
	first = filepath.Clean(first)
	second = filepath.Clean(second)
	return first == second || strings.HasPrefix(first, second+string(filepath.Separator)) || strings.HasPrefix(second, first+string(filepath.Separator))
}

func validLowerSHA256(value string) bool {
	if len(value) != 64 {
		return false
	}
	for _, r := range value {
		if (r < '0' || r > '9') && (r < 'a' || r > 'f') {
			return false
		}
	}
	return true
}

func buildNetworkRules(values []string) ([]config.NetworkRule, []config.NetworkRule, error) {
	rules := make([]config.NetworkRule, 0, len(values))
	wildcards := make([]config.NetworkRule, 0)
	for _, value := range values {
		rule, err := config.ParseNetworkRule(value)
		if err != nil {
			return nil, nil, err
		}
		rules = append(rules, rule)
		if rule.Wildcard {
			wildcards = append(wildcards, rule)
		}
	}
	sort.Slice(rules, func(i, j int) bool {
		return rules[i].Raw < rules[j].Raw
	})
	sort.Slice(wildcards, func(i, j int) bool {
		return wildcards[i].Raw < wildcards[j].Raw
	})
	return rules, wildcards, nil
}

// dnsHostsForRules separates exact DNS names from wildcard suffixes. Literal
// IP rules do not need resolver policy entries.
func dnsHostsForRules(ruleSets ...[]config.NetworkRule) ([]string, []string) {
	var exact []string
	var wildcards []string
	for _, rules := range ruleSets {
		for _, rule := range rules {
			if _, err := netip.ParseAddr(rule.Host); err == nil {
				continue
			}
			if rule.Wildcard {
				wildcards = append(wildcards, rule.Host)
			} else {
				exact = append(exact, rule.Host)
			}
		}
	}
	return uniqueSortedStrings(exact), uniqueSortedStrings(wildcards)
}

func uniqueSortedStrings(values []string) []string {
	seen := make(map[string]struct{}, len(values))
	result := make([]string, 0, len(values))
	for _, value := range values {
		if _, ok := seen[value]; ok {
			continue
		}
		seen[value] = struct{}{}
		result = append(result, value)
	}
	sort.Strings(result)
	return result
}

func buildMounts(mounts map[string]config.Mount, canonicalSources map[string]string) ([]mountData, error) {
	if canonicalSources != nil && len(canonicalSources) != len(mounts) {
		return nil, fmt.Errorf("canonical mount sources do not match configured mounts")
	}
	sources := make([]string, 0, len(mounts))
	for source := range mounts {
		sources = append(sources, source)
	}
	sort.Strings(sources)

	result := make([]mountData, 0, len(sources))
	for _, source := range sources {
		mount := mounts[source]
		location := canonicalSources[source]
		if canonicalSources == nil {
			var err error
			location, err = expandHostPath(source)
			if err != nil {
				return nil, err
			}
		}
		if location == "" || !utf8.ValidString(location) || strings.IndexByte(location, 0) >= 0 || !filepath.IsAbs(location) || filepath.Clean(location) != location {
			return nil, fmt.Errorf("canonical mount source for %q must be a clean absolute path", source)
		}
		result = append(result, mountData{
			Location: location,
			Target:   filepath.Clean(mount.Target),
			Writable: mount.Mode == "rw",
		})
	}
	return result, nil
}

func expandHostPath(path string) (string, error) {
	if path == "~" {
		home, err := os.UserHomeDir()
		if err != nil {
			return "", fmt.Errorf("expanding %q: %w", path, err)
		}
		return home, nil
	}
	if strings.HasPrefix(path, "~/") {
		home, err := os.UserHomeDir()
		if err != nil {
			return "", fmt.Errorf("expanding %q: %w", path, err)
		}
		return filepath.Join(home, strings.TrimPrefix(path, "~/")), nil
	}
	return path, nil
}

// provisionExposeBins returns best-effort CLI command names that should get wrappers
// for provisioned packages even when they already exist in the base image.
func provisionExposeBins(manager string, pkgs []string) ([]string, error) {
	if manager != "npm" {
		return nil, nil
	}

	seen := make(map[string]bool)
	var bins []string
	for _, pkg := range pkgs {
		bin := npmPackageToCommand(pkg)
		if bin == "" || seen[bin] {
			continue
		}
		if err := config.ValidateCommandName(bin); err != nil {
			return nil, fmt.Errorf("derived from package %q: %w", pkg, err)
		}
		seen[bin] = true
		bins = append(bins, bin)
	}
	return bins, nil
}

// npmPackageToCommand converts npm package specs to likely command names:
// - "pnpm" -> "pnpm"
// - "pnpm@10" -> "pnpm"
// - "@scope/name" -> "name"
// - "@scope/name@1.2.3" -> "name"
func npmPackageToCommand(pkg string) string {
	if pkg == "" {
		return ""
	}

	name := pkg
	if strings.HasPrefix(name, "@") {
		if slash := strings.LastIndex(name, "/"); slash >= 0 && slash+1 < len(name) {
			name = name[slash+1:]
		}
	}

	if at := strings.LastIndex(name, "@"); at > 0 {
		name = name[:at]
	}

	name = strings.TrimSpace(name)
	if name == "" {
		return ""
	}
	if strings.ContainsAny(name, config.ShellMetacharacters+" /") {
		return ""
	}
	return name
}

// convertMemory converts Watermelon's decimal-looking resource syntax to the
// binary unit spelling Lima expects.
func convertMemory(mem string) string {
	return convertResourceSize(mem)
}

// convertDisk converts Watermelon's decimal-looking resource syntax to the
// binary unit spelling Lima expects.
func convertDisk(disk string) string {
	return convertResourceSize(disk)
}

func convertResourceSize(size string) string {
	for _, unit := range []string{"MB", "GB", "TB"} {
		if strings.HasSuffix(size, unit) {
			return strings.TrimSuffix(size, unit) + string(unit[0]) + "iB"
		}
	}
	return size
}

func buildNetworkProcessImages(providers map[string]string, processes map[string][]string) map[string]string {
	images := make(map[string]string)
	for proc := range processes {
		if img := providers[proc]; img != "" {
			images[proc] = img
		}
	}
	return images
}

func collectUniqueImages(tools map[string][]string) []string {
	images := make([]string, 0, len(tools))
	for image := range tools {
		images = append(images, image)
	}
	sort.Strings(images)
	return images
}
